// The per-section llms.txt served at /docs/llms.txt and /news/llms.txt.
//
// Distinct from the repo-wide public/llms.txt (registry + API surfaces,
// generated by scripts/build-artifacts.ts and proxied onto this host by
// server.ts): these two are the PROSE indexes, sourced live from the fumadocs
// loaders so they grow with the content and need no build step.
//
// #11294: both now state the markdown-twin rule. The llms.txt convention is
// worth little if the links it lists all lead to HTML an agent has to strip --
// the value is in getting to clean markdown, and this site already compiles it
// for all 634 pages. Stating the rule once beats emitting a second URL per
// entry: the docs index alone is 349 entries / 39 KB, and doubling every line
// to say the same mechanical thing is how a context window gets spent on
// nothing. The per-page `rel="alternate"` link (see raw-markdown.ts) is the
// half that needs no convention known in advance.
import { rawMarkdownPath, type RawMarkdownSection } from "./raw-markdown";

export interface LlmsIndexOptions {
  /** The fumadocs loader's `llms(source).index()` output, with site-relative links. */
  index: string;
  section: RawMarkdownSection;
  /** The request's own origin, so dev and preview deploys are correct too. */
  origin: string;
  /**
   * The H1 this file should carry.
   *
   * Not the loader's: `llms()` hardcodes `# Docs` for every collection, so the
   * digests' index introduced itself as the documentation. An LLM index whose
   * title names the wrong body of work is worse than one with no title.
   */
  title: string;
  /** A real path in this section, used to show the twin rule rather than describe it. */
  example: string;
}

/**
 * Absolutize the loader's links, title the file, and state the twin rule.
 *
 * The absolutizing is load-bearing: a fumadocs loader's `baseUrl` makes
 * `index()` emit site-relative links, which are fine for in-app rendering and
 * useless in a plain-text file a machine fetches with no page context to
 * resolve `/docs/feeds` against.
 */
export function llmsIndexBody({
  index,
  section,
  origin,
  title,
  example,
}: LlmsIndexOptions): string {
  const lines = index.replace(/\]\(\//g, `](${origin}/`).split("\n");
  const note =
    `> Every page below is also served as plain markdown: insert \`raw/\` after ` +
    `\`/${section}/\` in any URL. ` +
    `${origin}/${section}/${example} -> ${origin}${rawMarkdownPath(section, example)}`;
  // The llms.txt shape is H1, one blockquote summary, then the details. A
  // note buried below 349 link lines is a note nothing reads.
  const h1 = lines.findIndex((line) => line.startsWith("# "));
  return h1 === -1
    ? [`# ${title}`, "", note, "", ...lines].join("\n")
    : [`# ${title}`, "", note, ...lines.slice(h1 + 1)].join("\n");
}

/** Headers both section indexes answer with. */
export function llmsIndexHeaders(): HeadersInit {
  return {
    "content-type": "text/plain; charset=utf-8",
    // Rebuilt from the compiled collections on every request, and the content
    // only changes on deploy.
    "cache-control": "public, max-age=300, stale-while-revalidate=86400",
  };
}
