/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DelegateRouteImport } from './routes/delegate'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsSs58RouteImport } from './routes/accounts.$ss58'
import { Route as AdminChangesIndexRouteImport } from './routes/admin-changes.index'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApisIndexRouteImport } from './routes/apis.index'
import { Route as ApisEndpointsRouteImport } from './routes/apis.endpoints'
import { Route as ApisProvidersRouteImport } from './routes/apis.providers'
import { Route as ApisSchemasRouteImport } from './routes/apis.schemas'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as BlocksRefRouteImport } from './routes/blocks.$ref'
import { Route as ChainIndexRouteImport } from './routes/chain.index'
import { Route as ChainAnalyticsRouteImport } from './routes/chain.analytics'
import { Route as ChainBlocksRouteImport } from './routes/chain.blocks'
import { Route as ChainEventsRouteImport } from './routes/chain.events'
import { Route as ChainExtrinsicsRouteImport } from './routes/chain.extrinsics'
import { Route as ChainGovernanceRouteImport } from './routes/chain.governance'
import { Route as ChainRuntimeRouteImport } from './routes/chain.runtime'
import { Route as DesignPrimitivesRouteImport } from './routes/design.primitives'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs.llms[.]txt'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ExtrinsicsIndexRouteImport } from './routes/extrinsics.index'
import { Route as ExtrinsicsHashRouteImport } from './routes/extrinsics.$hash'
import { Route as GraphqlExplorerRouteImport } from './routes/graphql.explorer'
import { Route as NewsSplatRouteImport } from './routes/news.$'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as RuntimeIndexRouteImport } from './routes/runtime.index'
import { Route as SubnetsIndexRouteImport } from './routes/subnets.index'
import { Route as SubnetsNetuidRouteImport } from './routes/subnets.$netuid'
import { Route as SudoIndexRouteImport } from './routes/sudo.index'
import { Route as ToolsSs58RouteImport } from './routes/tools.ss58'
import { Route as ValidatorsIndexRouteImport } from './routes/validators.index'
import { Route as ValidatorsHotkeyRouteImport } from './routes/validators.$hotkey'
import { Route as DocsRawSplatRouteImport } from './routes/docs.raw.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateRoute = DelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSs58Route = AccountsSs58RouteImport.update({
  id: '/accounts/$ss58',
  path: '/accounts/$ss58',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangesIndexRoute = AdminChangesIndexRouteImport.update({
  id: '/admin-changes/',
  path: '/admin-changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApisRoute,
} as any)
const ApisEndpointsRoute = ApisEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => ApisRoute,
} as any)
const ApisProvidersRoute = ApisProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ApisRoute,
} as any)
const ApisSchemasRoute = ApisSchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => ApisRoute,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRefRoute = BlocksRefRouteImport.update({
  id: '/blocks/$ref',
  path: '/blocks/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainIndexRoute = ChainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChainRoute,
} as any)
const ChainAnalyticsRoute = ChainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ChainRoute,
} as any)
const ChainBlocksRoute = ChainBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => ChainRoute,
} as any)
const ChainEventsRoute = ChainEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ChainRoute,
} as any)
const ChainExtrinsicsRoute = ChainExtrinsicsRouteImport.update({
  id: '/extrinsics',
  path: '/extrinsics',
  getParentRoute: () => ChainRoute,
} as any)
const ChainGovernanceRoute = ChainGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => ChainRoute,
} as any)
const ChainRuntimeRoute = ChainRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => ChainRoute,
} as any)
const DesignPrimitivesRoute = DesignPrimitivesRouteImport.update({
  id: '/design/primitives',
  path: '/design/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsIndexRoute = ExtrinsicsIndexRouteImport.update({
  id: '/extrinsics/',
  path: '/extrinsics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsHashRoute = ExtrinsicsHashRouteImport.update({
  id: '/extrinsics/$hash',
  path: '/extrinsics/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlExplorerRoute = GraphqlExplorerRouteImport.update({
  id: '/graphql/explorer',
  path: '/graphql/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSplatRoute = NewsSplatRouteImport.update({
  id: '/news/$',
  path: '/news/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeIndexRoute = RuntimeIndexRouteImport.update({
  id: '/runtime/',
  path: '/runtime/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsIndexRoute = SubnetsIndexRouteImport.update({
  id: '/subnets/',
  path: '/subnets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsNetuidRoute = SubnetsNetuidRouteImport.update({
  id: '/subnets/$netuid',
  path: '/subnets/$netuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SudoIndexRoute = SudoIndexRouteImport.update({
  id: '/sudo/',
  path: '/sudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSs58Route = ToolsSs58RouteImport.update({
  id: '/tools/ss58',
  path: '/tools/ss58',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsIndexRoute = ValidatorsIndexRouteImport.update({
  id: '/validators/',
  path: '/validators/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsHotkeyRoute = ValidatorsHotkeyRouteImport.update({
  id: '/validators/$hotkey',
  path: '/validators/$hotkey',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRawSplatRoute = DocsRawSplatRouteImport.update({
  id: '/docs/raw/$',
  path: '/docs/raw/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apis': typeof ApisRouteWithChildren
  '/chain': typeof ChainRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/delegate': typeof DelegateRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/apis/endpoints': typeof ApisEndpointsRoute
  '/apis/providers': typeof ApisProvidersRoute
  '/apis/schemas': typeof ApisSchemasRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/chain/analytics': typeof ChainAnalyticsRoute
  '/chain/blocks': typeof ChainBlocksRoute
  '/chain/events': typeof ChainEventsRoute
  '/chain/extrinsics': typeof ChainExtrinsicsRoute
  '/chain/governance': typeof ChainGovernanceRoute
  '/chain/runtime': typeof ChainRuntimeRoute
  '/design/primitives': typeof DesignPrimitivesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/news/$': typeof NewsSplatRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/apis/': typeof ApisIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/chain/': typeof ChainIndexRoute
  '/events/': typeof EventsIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runtime/': typeof RuntimeIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contribute': typeof ContributeRoute
  '/delegate': typeof DelegateRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/apis/endpoints': typeof ApisEndpointsRoute
  '/apis/providers': typeof ApisProvidersRoute
  '/apis/schemas': typeof ApisSchemasRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/chain/analytics': typeof ChainAnalyticsRoute
  '/chain/blocks': typeof ChainBlocksRoute
  '/chain/events': typeof ChainEventsRoute
  '/chain/extrinsics': typeof ChainExtrinsicsRoute
  '/chain/governance': typeof ChainGovernanceRoute
  '/chain/runtime': typeof ChainRuntimeRoute
  '/design/primitives': typeof DesignPrimitivesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/news/$': typeof NewsSplatRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts': typeof AccountsIndexRoute
  '/admin-changes': typeof AdminChangesIndexRoute
  '/apis': typeof ApisIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/chain': typeof ChainIndexRoute
  '/events': typeof EventsIndexRoute
  '/extrinsics': typeof ExtrinsicsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/runtime': typeof RuntimeIndexRoute
  '/subnets': typeof SubnetsIndexRoute
  '/sudo': typeof SudoIndexRoute
  '/validators': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apis': typeof ApisRouteWithChildren
  '/chain': typeof ChainRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/delegate': typeof DelegateRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/apis/endpoints': typeof ApisEndpointsRoute
  '/apis/providers': typeof ApisProvidersRoute
  '/apis/schemas': typeof ApisSchemasRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/chain/analytics': typeof ChainAnalyticsRoute
  '/chain/blocks': typeof ChainBlocksRoute
  '/chain/events': typeof ChainEventsRoute
  '/chain/extrinsics': typeof ChainExtrinsicsRoute
  '/chain/governance': typeof ChainGovernanceRoute
  '/chain/runtime': typeof ChainRuntimeRoute
  '/design/primitives': typeof DesignPrimitivesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/news/$': typeof NewsSplatRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/apis/': typeof ApisIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/chain/': typeof ChainIndexRoute
  '/events/': typeof EventsIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runtime/': typeof RuntimeIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/apis'
    | '/chain'
    | '/contribute'
    | '/delegate'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/apis/endpoints'
    | '/apis/providers'
    | '/apis/schemas'
    | '/blocks/$ref'
    | '/chain/analytics'
    | '/chain/blocks'
    | '/chain/events'
    | '/chain/extrinsics'
    | '/chain/governance'
    | '/chain/runtime'
    | '/design/primitives'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/news/$'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts/'
    | '/admin-changes/'
    | '/apis/'
    | '/blocks/'
    | '/chain/'
    | '/events/'
    | '/extrinsics/'
    | '/providers/'
    | '/runtime/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
    | '/docs/raw/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/contribute'
    | '/delegate'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/apis/endpoints'
    | '/apis/providers'
    | '/apis/schemas'
    | '/blocks/$ref'
    | '/chain/analytics'
    | '/chain/blocks'
    | '/chain/events'
    | '/chain/extrinsics'
    | '/chain/governance'
    | '/chain/runtime'
    | '/design/primitives'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/news/$'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts'
    | '/admin-changes'
    | '/apis'
    | '/blocks'
    | '/chain'
    | '/events'
    | '/extrinsics'
    | '/providers'
    | '/runtime'
    | '/subnets'
    | '/sudo'
    | '/validators'
    | '/docs/raw/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/apis'
    | '/chain'
    | '/contribute'
    | '/delegate'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/apis/endpoints'
    | '/apis/providers'
    | '/apis/schemas'
    | '/blocks/$ref'
    | '/chain/analytics'
    | '/chain/blocks'
    | '/chain/events'
    | '/chain/extrinsics'
    | '/chain/governance'
    | '/chain/runtime'
    | '/design/primitives'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/news/$'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts/'
    | '/admin-changes/'
    | '/apis/'
    | '/blocks/'
    | '/chain/'
    | '/events/'
    | '/extrinsics/'
    | '/providers/'
    | '/runtime/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
    | '/docs/raw/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ApisRoute: typeof ApisRouteWithChildren
  ChainRoute: typeof ChainRouteWithChildren
  ContributeRoute: typeof ContributeRoute
  DelegateRoute: typeof DelegateRoute
  DomainsRoute: typeof DomainsRoute
  EndpointsRoute: typeof EndpointsRoute
  ExplorerRoute: typeof ExplorerRoute
  GapsRoute: typeof GapsRoute
  HealthRoute: typeof HealthRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PortfolioRoute: typeof PortfolioRoute
  SchemasRoute: typeof SchemasRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SurfacesRoute: typeof SurfacesRoute
  AccountsSs58Route: typeof AccountsSs58Route
  ApiSearchRoute: typeof ApiSearchRoute
  BlocksRefRoute: typeof BlocksRefRoute
  DesignPrimitivesRoute: typeof DesignPrimitivesRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  ExtrinsicsHashRoute: typeof ExtrinsicsHashRoute
  GraphqlExplorerRoute: typeof GraphqlExplorerRoute
  NewsSplatRoute: typeof NewsSplatRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  SubnetsNetuidRoute: typeof SubnetsNetuidRoute
  ToolsSs58Route: typeof ToolsSs58Route
  ValidatorsHotkeyRoute: typeof ValidatorsHotkeyRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AdminChangesIndexRoute: typeof AdminChangesIndexRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ExtrinsicsIndexRoute: typeof ExtrinsicsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  RuntimeIndexRoute: typeof RuntimeIndexRoute
  SubnetsIndexRoute: typeof SubnetsIndexRoute
  SudoIndexRoute: typeof SudoIndexRoute
  ValidatorsIndexRoute: typeof ValidatorsIndexRoute
  DocsRawSplatRoute: typeof DocsRawSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate': {
      id: '/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof DelegateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$ss58': {
      id: '/accounts/$ss58'
      path: '/accounts/$ss58'
      fullPath: '/accounts/$ss58'
      preLoaderRoute: typeof AccountsSs58RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-changes/': {
      id: '/admin-changes/'
      path: '/admin-changes'
      fullPath: '/admin-changes/'
      preLoaderRoute: typeof AdminChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/': {
      id: '/apis/'
      path: '/'
      fullPath: '/apis/'
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof ApisRoute
    }
    '/apis/endpoints': {
      id: '/apis/endpoints'
      path: '/endpoints'
      fullPath: '/apis/endpoints'
      preLoaderRoute: typeof ApisEndpointsRouteImport
      parentRoute: typeof ApisRoute
    }
    '/apis/providers': {
      id: '/apis/providers'
      path: '/providers'
      fullPath: '/apis/providers'
      preLoaderRoute: typeof ApisProvidersRouteImport
      parentRoute: typeof ApisRoute
    }
    '/apis/schemas': {
      id: '/apis/schemas'
      path: '/schemas'
      fullPath: '/apis/schemas'
      preLoaderRoute: typeof ApisSchemasRouteImport
      parentRoute: typeof ApisRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$ref': {
      id: '/blocks/$ref'
      path: '/blocks/$ref'
      fullPath: '/blocks/$ref'
      preLoaderRoute: typeof BlocksRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain/': {
      id: '/chain/'
      path: '/'
      fullPath: '/chain/'
      preLoaderRoute: typeof ChainIndexRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/analytics': {
      id: '/chain/analytics'
      path: '/analytics'
      fullPath: '/chain/analytics'
      preLoaderRoute: typeof ChainAnalyticsRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/blocks': {
      id: '/chain/blocks'
      path: '/blocks'
      fullPath: '/chain/blocks'
      preLoaderRoute: typeof ChainBlocksRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/events': {
      id: '/chain/events'
      path: '/events'
      fullPath: '/chain/events'
      preLoaderRoute: typeof ChainEventsRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/extrinsics': {
      id: '/chain/extrinsics'
      path: '/extrinsics'
      fullPath: '/chain/extrinsics'
      preLoaderRoute: typeof ChainExtrinsicsRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/governance': {
      id: '/chain/governance'
      path: '/governance'
      fullPath: '/chain/governance'
      preLoaderRoute: typeof ChainGovernanceRouteImport
      parentRoute: typeof ChainRoute
    }
    '/chain/runtime': {
      id: '/chain/runtime'
      path: '/runtime'
      fullPath: '/chain/runtime'
      preLoaderRoute: typeof ChainRuntimeRouteImport
      parentRoute: typeof ChainRoute
    }
    '/design/primitives': {
      id: '/design/primitives'
      path: '/design/primitives'
      fullPath: '/design/primitives'
      preLoaderRoute: typeof DesignPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/': {
      id: '/extrinsics/'
      path: '/extrinsics'
      fullPath: '/extrinsics/'
      preLoaderRoute: typeof ExtrinsicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/$hash': {
      id: '/extrinsics/$hash'
      path: '/extrinsics/$hash'
      fullPath: '/extrinsics/$hash'
      preLoaderRoute: typeof ExtrinsicsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql/explorer': {
      id: '/graphql/explorer'
      path: '/graphql/explorer'
      fullPath: '/graphql/explorer'
      preLoaderRoute: typeof GraphqlExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$': {
      id: '/news/$'
      path: '/news/$'
      fullPath: '/news/$'
      preLoaderRoute: typeof NewsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/': {
      id: '/runtime/'
      path: '/runtime'
      fullPath: '/runtime/'
      preLoaderRoute: typeof RuntimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/': {
      id: '/subnets/'
      path: '/subnets'
      fullPath: '/subnets/'
      preLoaderRoute: typeof SubnetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/$netuid': {
      id: '/subnets/$netuid'
      path: '/subnets/$netuid'
      fullPath: '/subnets/$netuid'
      preLoaderRoute: typeof SubnetsNetuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudo/': {
      id: '/sudo/'
      path: '/sudo'
      fullPath: '/sudo/'
      preLoaderRoute: typeof SudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ss58': {
      id: '/tools/ss58'
      path: '/tools/ss58'
      fullPath: '/tools/ss58'
      preLoaderRoute: typeof ToolsSs58RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/': {
      id: '/validators/'
      path: '/validators'
      fullPath: '/validators/'
      preLoaderRoute: typeof ValidatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/$hotkey': {
      id: '/validators/$hotkey'
      path: '/validators/$hotkey'
      fullPath: '/validators/$hotkey'
      preLoaderRoute: typeof ValidatorsHotkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/raw/$': {
      id: '/docs/raw/$'
      path: '/docs/raw/$'
      fullPath: '/docs/raw/$'
      preLoaderRoute: typeof DocsRawSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApisRouteChildren {
  ApisEndpointsRoute: typeof ApisEndpointsRoute
  ApisProvidersRoute: typeof ApisProvidersRoute
  ApisSchemasRoute: typeof ApisSchemasRoute
  ApisIndexRoute: typeof ApisIndexRoute
}

const ApisRouteChildren: ApisRouteChildren = {
  ApisEndpointsRoute: ApisEndpointsRoute,
  ApisProvidersRoute: ApisProvidersRoute,
  ApisSchemasRoute: ApisSchemasRoute,
  ApisIndexRoute: ApisIndexRoute,
}

const ApisRouteWithChildren = ApisRoute._addFileChildren(ApisRouteChildren)

interface ChainRouteChildren {
  ChainAnalyticsRoute: typeof ChainAnalyticsRoute
  ChainBlocksRoute: typeof ChainBlocksRoute
  ChainEventsRoute: typeof ChainEventsRoute
  ChainExtrinsicsRoute: typeof ChainExtrinsicsRoute
  ChainGovernanceRoute: typeof ChainGovernanceRoute
  ChainRuntimeRoute: typeof ChainRuntimeRoute
  ChainIndexRoute: typeof ChainIndexRoute
}

const ChainRouteChildren: ChainRouteChildren = {
  ChainAnalyticsRoute: ChainAnalyticsRoute,
  ChainBlocksRoute: ChainBlocksRoute,
  ChainEventsRoute: ChainEventsRoute,
  ChainExtrinsicsRoute: ChainExtrinsicsRoute,
  ChainGovernanceRoute: ChainGovernanceRoute,
  ChainRuntimeRoute: ChainRuntimeRoute,
  ChainIndexRoute: ChainIndexRoute,
}

const ChainRouteWithChildren = ChainRoute._addFileChildren(ChainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ApisRoute: ApisRouteWithChildren,
  ChainRoute: ChainRouteWithChildren,
  ContributeRoute: ContributeRoute,
  DelegateRoute: DelegateRoute,
  DomainsRoute: DomainsRoute,
  EndpointsRoute: EndpointsRoute,
  ExplorerRoute: ExplorerRoute,
  GapsRoute: GapsRoute,
  HealthRoute: HealthRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PortfolioRoute: PortfolioRoute,
  SchemasRoute: SchemasRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SurfacesRoute: SurfacesRoute,
  AccountsSs58Route: AccountsSs58Route,
  ApiSearchRoute: ApiSearchRoute,
  BlocksRefRoute: BlocksRefRoute,
  DesignPrimitivesRoute: DesignPrimitivesRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  ExtrinsicsHashRoute: ExtrinsicsHashRoute,
  GraphqlExplorerRoute: GraphqlExplorerRoute,
  NewsSplatRoute: NewsSplatRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  SubnetsNetuidRoute: SubnetsNetuidRoute,
  ToolsSs58Route: ToolsSs58Route,
  ValidatorsHotkeyRoute: ValidatorsHotkeyRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AdminChangesIndexRoute: AdminChangesIndexRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ExtrinsicsIndexRoute: ExtrinsicsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  RuntimeIndexRoute: RuntimeIndexRoute,
  SubnetsIndexRoute: SubnetsIndexRoute,
  SudoIndexRoute: SudoIndexRoute,
  ValidatorsIndexRoute: ValidatorsIndexRoute,
  DocsRawSplatRoute: DocsRawSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
