import assert from "node:assert/strict";
import { describe, test } from "vitest";
import { Ajv2020 } from "ajv/dist/2020.js";
import {
  SELF_HEALTH_ARTIFACT,
  GET_SELF_HEALTH_INSTRUCTIONS,
  GET_SELF_HEALTH_MCP_TOOL,
  GET_SELF_HEALTH_OUTPUT_SCHEMA,
  selfHealthToolError,
  loadSelfHealth,
} from "../src/self-health-mcp.ts";
import { MCP_INSTRUCTIONS, MCP_TOOLS } from "../src/mcp-server.ts";
import type { StorageReadResult } from "../workers/storage.ts";
import { mockEnv, type Row } from "./row-type.ts";

type ReadArtifact = (env: Env, path: string) => Promise<StorageReadResult>;

const SAMPLE_SELF_HEALTH = {
  schema_version: 1,
  verdict: "operational",
  components: [
    {
      component: "api",
      current_ok: true,
      http_status: 200,
      latency_ms: 42,
      checked_at: "2026-07-01T00:00:00.000Z",
      note: null,
      days: [
        { day: "2026-06-30", checks: 1440, ok_count: 1440, uptime_ratio: 1 },
      ],
      uptime_90d: 0.999,
    },
    {
      component: "site",
      current_ok: null,
      http_status: null,
      latency_ms: null,
      checked_at: null,
      note: null,
      days: [],
      uptime_90d: null,
    },
  ],
  measured_component_count: 1,
  lanes: [
    {
      lane: "chain-detail",
      verdict: "stale",
      age_ms: 14_400_000,
      detail: "hot_window.to frozen at 8,765,682",
      checked_at: "2026-07-01T00:00:00.000Z",
    },
  ],
  stale_lane_count: 1,
  observed_at: "2026-07-01T00:00:00.000Z",
};

describe("self-health-mcp", () => {
  test("selfHealthToolError is shaped for MCP toolError handling", () => {
    const err = selfHealthToolError("not_found", "missing");
    assert.equal(err.code, "not_found");
    assert.equal(err.toolError, true);
    assert.equal(err.message, "missing");
  });

  test("loadSelfHealth returns the baked artifact payload", async () => {
    const ctx = {
      env: mockEnv(),
      readArtifact: (async (_env: Env, path: string) => ({
        ok: true,
        data: path === SELF_HEALTH_ARTIFACT ? SAMPLE_SELF_HEALTH : null,
      })) as unknown as ReadArtifact,
    };
    const out = (await loadSelfHealth(ctx)) as Row;
    assert.equal(out.schema_version, 1);
    assert.equal(out.verdict, "operational");
    assert.equal(out.components.length, 2);
    assert.equal(out.components[0].days[0].uptime_ratio, 1);
  });

  test("loadSelfHealth uses an injected readArtifact dep", async () => {
    const out = (await loadSelfHealth(
      {
        env: mockEnv(),
        readArtifact: (async () => ({ ok: false })) as unknown as ReadArtifact,
      },
      {
        readArtifact: (async () => ({
          ok: true,
          data: {
            schema_version: 1,
            verdict: "degraded",
            components: [],
            measured_component_count: 0,
            observed_at: null,
          },
        })) as unknown as ReadArtifact,
      },
    )) as Row;
    assert.equal(out.verdict, "degraded");
  });

  // #8633: the artifact this loader used to read FIRST has never been written
  // by anything -- absent from public/metagraph/, generated by no script or
  // workflow. So `artifact_not_found` was production's only state, and both
  // get_self_health and the GraphQL selfHealth field returned not_found while
  // GET /api/v1/self-health returned verdict "operational". These pin the
  // resolution order that fixes it: live tier, then artifact, then the
  // schema-stable empty shape.
  const tierEnv = (fetchImpl: (request: Request) => Promise<Response>) => {
    const env = mockEnv() as unknown as Row;
    env.METAGRAPH_SELF_HEALTH_SOURCE = "postgres";
    env.DATA_API = { fetch: fetchImpl };
    return env as unknown as Env;
  };
  const artifactNotFound = (async () => ({
    ok: false,
    code: "artifact_not_found",
  })) as unknown as ReadArtifact;

  test("prefers the LIVE tier over a baked artifact, so all three surfaces agree", async () => {
    // Even with a perfectly good artifact present, the tier wins: self-health
    // is live probe data and a bake would serve a stale verdict.
    //
    // #8987: the body here is the document BARE. It used to be
    // `{ ok: true, data: SAMPLE_SELF_HEALTH }`, which is a shape the DATA_API
    // binding never produces -- workers/data-api.ts's `json()` serializes the
    // value directly. That fiction is why this test passed for a month while
    // get_self_health served all-nulls in production: the test asserted the
    // envelope the code expected instead of the one the producer emits.
    const stale = { ...SAMPLE_SELF_HEALTH, verdict: "outage" };
    const out = (await loadSelfHealth({
      env: tierEnv(async (request) => {
        assert.equal(new URL(request.url).pathname, "/api/v1/self-health");
        return new Response(JSON.stringify(SAMPLE_SELF_HEALTH), {
          headers: { "content-type": "application/json" },
        });
      }),
      readArtifact: (async () => ({
        ok: true,
        data: stale,
      })) as unknown as ReadArtifact,
    })) as Row;
    assert.equal(out.verdict, "operational");
  });

  test("falls back to the artifact when no tier is configured", async () => {
    // Dev/test and any fixture-backed environment: the artifact path is kept
    // deliberately, not deleted.
    const out = (await loadSelfHealth({
      env: mockEnv(),
      readArtifact: (async () => ({
        ok: true,
        data: SAMPLE_SELF_HEALTH,
      })) as unknown as ReadArtifact,
    })) as Row;
    assert.equal(out.verdict, "operational");
  });

  test("an absent artifact and no tier returns the empty shape, never an error", async () => {
    // handleSelfHealth's own convention: "we have no readings" is a real
    // state answered with data, not a 404.
    const out = (await loadSelfHealth({
      env: mockEnv(),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
    assert.equal((out.components as Row[]).length, 3);
    assert.equal((out.components as Row[])[0]!.current_ok, null);
  });

  test("a tier that throws degrades to the artifact rather than failing the call", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(async () => {
        throw new Error("binding exploded");
      }),
      readArtifact: (async () => ({
        ok: true,
        data: SAMPLE_SELF_HEALTH,
      })) as unknown as ReadArtifact,
    })) as Row;
    assert.equal(out.verdict, "operational");
  });

  // A non-2xx from the binding degrades before the body is even read. This
  // branch was untested before #8987 -- which is part of why the whole
  // function could return null on every call without anything going red.
  test("a tier returning a non-2xx status is treated as no data", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response(JSON.stringify(SAMPLE_SELF_HEALTH), {
            status: 503,
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
  });

  test("a tier returning an error body is treated as no data", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response(JSON.stringify({ ok: false, error: { code: "boom" } }), {
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
  });

  // #8987 REGRESSION PIN. The old code required `{ ok, data }` and unwrapped
  // `.data`; nothing upstream emits that, so the live tier was dead. Asserting
  // the wrapped form is NOT accepted is what stops a future edit from
  // reintroducing envelope-unwrapping "for compatibility" -- if data-api is
  // ever changed to wrap its responses, this fails loudly and points here,
  // rather than the MCP tool silently going all-null again.
  test("an { ok, data } envelope is NOT accepted -- the binding returns bare", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response(JSON.stringify({ ok: true, data: SAMPLE_SELF_HEALTH }), {
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
  });

  // The exact production symptom of #8987, end to end: a healthy live tier and
  // an absent artifact (production's real state -- nothing has ever written
  // /metagraph/self-health.json) must yield the LIVE verdict, not the empty
  // shape. Before the fix this returned verdict "degraded" with three all-null
  // components and measured_component_count 0.
  test("a healthy tier with NO artifact serves the live verdict", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response(JSON.stringify(SAMPLE_SELF_HEALTH), {
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "operational");
    assert.equal(out.measured_component_count, 1);
    assert.equal((out.components as Row[])[0]!.current_ok, true);
  });

  // `typeof null === "object"` is true, so the null check is load-bearing
  // rather than defensive noise -- without it this throws on `.components`.
  test("a tier returning a JSON null body degrades", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response("null", {
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
  });

  // A 200 carrying something that is not a self-health document degrades
  // instead of being handed to an agent as if it were one.
  test("a tier returning a non-document body degrades", async () => {
    const out = (await loadSelfHealth({
      env: tierEnv(
        async () =>
          new Response(JSON.stringify("not a document"), {
            headers: { "content-type": "application/json" },
          }),
      ),
      readArtifact: artifactNotFound,
    })) as Row;
    assert.equal(out.verdict, "degraded");
  });

  test("loadSelfHealth surfaces other artifact failures with the path", async () => {
    const ctx = {
      env: mockEnv(),
      readArtifact: (async () => ({
        ok: false,
        code: "artifact_timeout",
      })) as unknown as ReadArtifact,
    };
    await assert.rejects(
      () => loadSelfHealth(ctx),
      (err: Row) =>
        err.code === "artifact_timeout" &&
        /self-health\.json/.test(err.message),
    );
  });

  test("loadSelfHealth defaults code when the read result is bare", async () => {
    const ctx = {
      env: mockEnv(),
      readArtifact: (async () => ({ ok: false })) as unknown as ReadArtifact,
    };
    await assert.rejects(
      () => loadSelfHealth(ctx),
      (err: Row) => err.code === "artifact_unavailable",
    );
  });

  test("MCP tool metadata and outputSchema compile", () => {
    assert.equal(GET_SELF_HEALTH_MCP_TOOL.name, "get_self_health");
    assert.match(GET_SELF_HEALTH_INSTRUCTIONS, /get_self_health/);
    assert.deepEqual(
      Object.keys(GET_SELF_HEALTH_MCP_TOOL.inputSchema.properties ?? {}),
      [],
    );
    assert.ok(
      new Ajv2020({ strict: false }).compile(GET_SELF_HEALTH_OUTPUT_SCHEMA),
    );
  });

  test("SAMPLE_SELF_HEALTH validates against GET_SELF_HEALTH_OUTPUT_SCHEMA", () => {
    const validate = new Ajv2020({ strict: false }).compile(
      GET_SELF_HEALTH_OUTPUT_SCHEMA,
    );
    assert.ok(validate(SAMPLE_SELF_HEALTH));
  });

  // #9330/#9340 + the cold-tier parity gap found live on 2026-08-04.
  //
  // These belong together because the second bug is what made the first invisible on
  // this surface: with METAGRAPH_SELF_HEALTH_SOURCE at "retired" the live tier never
  // answers, so everything an agent sees comes from the tiers below it.
  describe("parity with the REST route", () => {
    function coldTierEnv(rows: Record<string, unknown>[]) {
      // r2SqlQuery reaches the lakehouse over fetch; a token makes it "configured".
      const env = mockEnv() as unknown as Row;
      env.R2_SQL_TOKEN = "test-token";
      env.METAGRAPH_SELF_HEALTH_SOURCE = "retired";
      const originalFetch = globalThis.fetch;
      globalThis.fetch = (async () =>
        new Response(JSON.stringify({ success: true, result: { rows } }), {
          status: 200,
          headers: { "content-type": "application/json" },
        })) as typeof fetch;
      return {
        env: env as unknown as Env,
        restore: () => {
          globalThis.fetch = originalFetch;
        },
      };
    }

    const NOT_FOUND = (async () => ({
      ok: false,
      code: "artifact_not_found",
    })) as unknown as ReadArtifact;

    test("serves the lakehouse rollup instead of an empty card", async () => {
      // The live regression: REST returned seven days per component while this loader
      // returned days: [] and uptime_90d: null for all three, because #9153 gave the
      // cold tier to the route and not to us.
      const { env, restore } = coldTierEnv([
        { day: "2026-08-01", component: "api", checks: 1440, ok_count: 1439 },
        { day: "2026-08-02", component: "api", checks: 482, ok_count: 482 },
      ]);
      try {
        const result = (await loadSelfHealth({
          env,
          readArtifact: NOT_FOUND,
        })) as Row;
        const api = (result.components as Row[]).find(
          (c) => c.component === "api",
        ) as Row;
        assert.equal((api.days as unknown[]).length, 2);
        assert.ok((api.uptime_90d as number) > 0.99);
      } finally {
        restore();
      }
    });

    test("an unreachable lakehouse still yields the empty card, not an error", async () => {
      const env = mockEnv() as unknown as Row;
      env.METAGRAPH_SELF_HEALTH_SOURCE = "retired";
      const result = (await loadSelfHealth({
        env: env as unknown as Env,
        readArtifact: NOT_FOUND,
      })) as Row;
      assert.equal((result.components as unknown[]).length, 3);
      assert.equal(result.measured_component_count, 0);
    });

    test("lane verdicts reach the MCP card, not only the REST one", async () => {
      const env = mockEnv() as unknown as Row;
      env.METAGRAPH_SELF_HEALTH_SOURCE = "retired";
      env.METAGRAPH_HEALTH_DB = {
        prepare: () => ({
          all: async () => ({
            results: [
              {
                lane: "chain-detail",
                verdict: "stale",
                age_ms: 14_400_000,
                detail: "frozen",
                checked_at: 1_785_800_000_000,
              },
            ],
          }),
        }),
      };
      const result = (await loadSelfHealth({
        env: env as unknown as Env,
        readArtifact: NOT_FOUND,
      })) as Row;
      assert.deepEqual(
        (result.lanes as Row[]).map((l) => l.lane),
        ["chain-detail"],
      );
      assert.equal(result.stale_lane_count, 1);
    });

    test("the MCP output schema IS the route schema, so they cannot drift", async () => {
      // These were two hand-kept copies and had already drifted (latency_ms typed as a
      // float here, an int on the route; verdict a bare string here, an enum there).
      const { SelfHealthArtifactSchema } =
        await import("../schemas-src/routes/self-health.ts");
      const { GetSelfHealthOutputSchema } =
        await import("../schemas-src/mcp-tools/meta-artifacts-2.ts");
      assert.equal(GetSelfHealthOutputSchema, SelfHealthArtifactSchema);
    });
  });

  test("MCP server exports wire get_self_health", () => {
    assert.match(MCP_INSTRUCTIONS, /get_self_health/);
    const tool = MCP_TOOLS.find((t) => t.name === "get_self_health");
    assert.ok(tool);
    assert.equal(tool.title, GET_SELF_HEALTH_MCP_TOOL.title);
  });
});
