// #10442/#10483/#10516: golden values first, then the two directions the guard
// can fail in.
//
// The three goldens were observed in production before the derivation was
// known -- SN64's turned up while tracing Chutes payments (#10448) and was very
// nearly recorded as a Chutes revenue collector. They are the reason this
// module exists, so they are the reason it is tested.
import assert from "node:assert/strict";
import { describe, test } from "vitest";
import {
  MAX_NETUID,
  isProtocolSubnetAccount,
  protocolSubnetNetuid,
  subnetAccountId,
  subnetAccountSs58,
} from "../src/subnet-accounts.ts";
import { DEFAULT_SS58_PREFIX, encodeAccountId32 } from "../src/ss58.ts";

// Independently observed on mainnet, 2026-08-10 — not generated by this module.
const GOLDEN: Record<number, string> = {
  0: "5EYCAe5jLQhn6ofDSvqF6iY53erXNkwhyE1aCEgvi1NNs91F",
  44: "5EYCAe5jLQhn6ofDSw3BjtVwyQbDX7QCLmMzRiuh4KrSienC",
  64: "5EYCAe5jLQhn6ofDSw8caRPiDJ7AgBRh4CABSaeQJqM278gq",
};

describe("subnet protocol accounts (#10442)", () => {
  test("derives the observed production addresses", () => {
    for (const [netuid, expected] of Object.entries(GOLDEN)) {
      assert.equal(subnetAccountSs58(Number(netuid)), expected);
    }
  });

  test("recognises them back, and reports the right netuid", () => {
    for (const [netuid, address] of Object.entries(GOLDEN)) {
      assert.equal(protocolSubnetNetuid(address), Number(netuid));
      assert.equal(isProtocolSubnetAccount(address), true);
    }
  });

  test("round-trips across the whole u16 range", () => {
    for (const netuid of [0, 1, 63, 64, 128, 255, 256, 1000, MAX_NETUID]) {
      const address = subnetAccountSs58(netuid);
      assert.ok(address, `no address for ${netuid}`);
      assert.equal(protocolSubnetNetuid(address), netuid);
    }
  });

  test("netuid 256 is not confused with netuid 1 — the second byte is read", () => {
    // A u16 written as a single byte would alias 256 onto 1, quietly mapping a
    // real subnet's account to the wrong subnet.
    assert.notEqual(subnetAccountSs58(256), subnetAccountSs58(1));
    assert.equal(protocolSubnetNetuid(subnetAccountSs58(256)), 256);
  });

  test("rejects an out-of-range netuid rather than truncating it", () => {
    // Truncation would return another live subnet's account.
    for (const bad of [-1, 65536, 1.5, Number.NaN, Number.POSITIVE_INFINITY]) {
      assert.equal(subnetAccountId(bad), null, `accepted ${bad}`);
      assert.equal(subnetAccountSs58(bad), null, `accepted ${bad}`);
    }
  });

  test("ordinary accounts are not protocol accounts", () => {
    // Real addresses seen in the Chutes payment feed, plus junk.
    for (const other of [
      "5FRYKhbmfXPDoHdUUDMx27E3HuMvAzwjzFMMq3rNurUhAyS9",
      "5CS3g6nVJM6ouns8n9buN9CzFf2C1YDHVcVGRcxoirKs2xbV",
      "5DJJAZLqnR3P4Um1UFuuZQ9DFVqoGwmeDXvcZDVPhH5V9NUY",
      "not-an-address",
      "",
    ]) {
      assert.equal(protocolSubnetNetuid(other), null, `matched ${other}`);
      assert.equal(isProtocolSubnetAccount(other), false);
    }
    assert.equal(protocolSubnetNetuid(null), null);
    assert.equal(protocolSubnetNetuid(undefined), null);
  });

  test("an address merely STARTING with the pallet prefix is rejected", () => {
    // The dangerous direction: if the trailing padding were not checked, an
    // attacker could craft a key whose first 12 bytes match and have the guard
    // exempt an address of their choosing.
    const forged = new Uint8Array(32);
    forged.set(subnetAccountId(64) as Uint8Array, 0);
    forged[20] = 0x01; // dirty the padding
    const address = encodeAccountId32(forged, DEFAULT_SS58_PREFIX);
    assert.ok(address);
    assert.equal(protocolSubnetNetuid(address), null);
  });

  test("another pallet's derived account is not a subnet account", () => {
    // Substrate derives every pallet account the same way, so `modl` alone is
    // not enough -- the treasury's own account would otherwise be exempted
    // from the revenue/treasury guard as though it were a subnet pool.
    const treasury = new Uint8Array(32);
    treasury.set([0x6d, 0x6f, 0x64, 0x6c], 0); // "modl"
    treasury.set(
      [0x70, 0x79, 0x2f, 0x74, 0x72, 0x73, 0x72, 0x79], // "py/trsry"
      4,
    );
    const address = encodeAccountId32(treasury, DEFAULT_SS58_PREFIX);
    assert.ok(address);
    assert.equal(protocolSubnetNetuid(address), null);
    assert.equal(isProtocolSubnetAccount(address), false);
  });

  test("re-encoding under a different SS58 prefix does not evade the guard", () => {
    // The guard decodes to the public key, so the network prefix is irrelevant.
    const polkadotPrefixed = encodeAccountId32(
      subnetAccountId(64) as Uint8Array,
      0,
    );
    assert.ok(polkadotPrefixed);
    assert.notEqual(polkadotPrefixed, GOLDEN[64]);
    assert.equal(protocolSubnetNetuid(polkadotPrefixed), 64);
  });

  test("a bad checksum is rejected", () => {
    const corrupted =
      GOLDEN[64].slice(0, -1) + (GOLDEN[64].endsWith("q") ? "r" : "q");
    assert.equal(protocolSubnetNetuid(corrupted), null);
  });
});
