// The all-tables freshness sweep (src/table-freshness-watchdog.ts, #9786).
//
// The test that gives this file its value is the COVERAGE one: every table in
// tests/fixtures/sqlite-schema must be classified, so a new table cannot arrive unwatched.
// That is the whole failure this watchdog exists to end -- four tables were
// frozen for five days because no per-lane watchdog covered them, and none
// ever would have.
//
// `maxAgeMs: null` is a classification, not an exemption: it says "staleness
// is meaningless here" and has to be written down. Absent from the list means
// nobody thought about it, and that fails.
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, test } from "vitest";
import { tablesInMigrations } from "../scripts/validate-declared-tables-exist.ts";
import {
  crossCheckSql,
  confirmRedirectedStale,
  crossCheckStamps,
  describeStaleTables,
  FRESHNESS_BATCH,
  freshnessSql,
  freshnessTables,
  parseFreshnessRows,
  runTableFreshnessWatchdog,
  staleTables,
  stampDivergences,
  TABLE_FRESHNESS,
  TABLE_FRESHNESS_LANE,
  type FreshnessExpectation,
} from "../src/table-freshness-watchdog.ts";
// Imported, not spelled as a literal: the registry cluster's `coveredBy` has to
// stay pinned to the lane the producer actually writes, so renaming that lane
// breaks this test instead of silently orphaning four tables (#10657).
import { REGISTRY_SYNC_LANE } from "../src/registry-sync-lane.ts";

const HOUR = 60 * 60 * 1000;
const NOW = 1_785_800_000_000;

function fakeDb(
  byTable: Record<string, unknown>,
  failOn: string[] = [],
  // The cross-check asks a different shape -- `{t, cheap, actual}` rather than
  // `{t, mx}` -- so the fake has to answer it as a different statement, not as
  // the sweep with extra columns.
  crossCheck: Record<
    string,
    { cheap: number | null; actual: number | null }
  > = {},
) {
  const calls: string[] = [];
  const written: Record<string, unknown>[] = [];
  return {
    calls,
    written,
    db: {
      async query(sql: string) {
        calls.push(sql);
        if (failOn.some((f) => sql.includes(f))) {
          throw new Error("store: overloaded");
        }
        const names = [...sql.matchAll(/SELECT '(\w+)' AS t/g)].map(
          (m) => m[1],
        );
        if (sql.includes("AS cheap")) {
          return names.map((t) => ({
            t,
            cheap: crossCheck[t]?.cheap ?? null,
            actual: crossCheck[t]?.actual ?? null,
          }));
        }
        return names.map((t) => ({ t, mx: byTable[t] ?? null }));
      },
      async run(sql: string, values: unknown[] = []) {
        calls.push(sql);
        if (sql.startsWith("INSERT")) {
          written.push({
            lane: values[0],
            verdict: values[1],
            age: values[2],
            detail: values[3],
          });
        }
        return { changes: 1 };
      },
    },
  };
}

/**
 * Every table this repo has committed to, from BOTH halves of the record.
 *
 * `db/schema.sql` is the snapshot of the live Neon schema, regenerated by
 * scripts/snapshot-neon-schema.ts and gated by validate:db-types-drift, so it
 * cannot quietly fall behind the store the sweep runs against -- the property
 * the old sqlite-schema fixture census did not have (#10817).
 *
 * IT IS NOT ENOUGH ON ITS OWN, and the gap cost two PRs (#11042). The snapshot
 * only learns about a table AFTER its migration applies, which happens on
 * merge -- so the PR that ADDS a table cannot classify it (the snapshot has
 * never heard of it) and cannot leave it unclassified either, because the
 * refresh-neon-schema drift PR that follows carries the snapshot and fails
 * this test. `treasury_readings` (#11025 -> #11030) and `compute_declarations`
 * (#11041 -> #11047) both went that way, two for two.
 *
 * Worse than the inconvenience: between those two merges the table is live,
 * written, and watched by nothing -- exactly the condition #9786 built this
 * watchdog to end.
 *
 * So the census is the UNION with the migrations, which name a table from the
 * commit that declares it. `tablesInMigrations` is IMPORTED from the validator
 * that already parses them rather than re-implemented here: it strips comments
 * first, because several migrations discuss tables they do not create, and a
 * second scanner is a second chance to get that wrong.
 *
 * The union is safe in the other direction too -- no migration in this repo
 * drops or renames a table, so nothing in it names something that stopped
 * existing. If one ever does, the "names no table that does not exist" test
 * below is what has to learn about it.
 */
export function tableCensus(
  liveSql: string,
  declared: Iterable<string>,
): Set<string> {
  const live = [...liveSql.matchAll(/CREATE TABLE public\.(\w+)/g)].map(
    (m) => m[1]!,
  );
  return new Set([...live, ...declared]);
}

function neonTables(): Set<string> {
  return tableCensus(
    readFileSync(path.join(process.cwd(), "db/schema.sql"), "utf8"),
    tablesInMigrations(path.join(process.cwd(), "migrations/neon")).keys(),
  );
}

describe("TABLE_FRESHNESS coverage", () => {
  test("every table the repo has committed to is classified", () => {
    // THE LOAD-BEARING TEST. A table absent from the map is one nobody has
    // decided the freshness meaning of, and it would be swept by nothing --
    // exactly how the registry cluster went five days unnoticed (#9779).
    //
    // THE CENSUS IS db/schema.sql UNION the migrations -- see neonTables. It
    // was tests/fixtures/sqlite-schema until #10817 (the frozen D1-era set: 49
    // tables, exactly the 49 the map classified, so it could never fail on a
    // Neon-era table however long it went unwatched -- fourteen had), and the
    // live snapshot alone until #11042, which could not see a table until its
    // migration had already applied.
    const declared = neonTables();
    assert.ok(
      declared.size >= 60,
      `only ${declared.size} tables parsed out of db/schema.sql plus ` +
        `migrations/neon -- the parse broke, so this test is passing on nothing`,
    );
    const missing = [...declared].filter((t) => !TABLE_FRESHNESS[t]).sort();
    assert.deepEqual(
      missing,
      [],
      "these tables have no freshness classification. Add them to " +
        "TABLE_FRESHNESS -- `maxAgeMs: null` with a reason is a valid answer, " +
        `being absent is not:\n${missing.join("\n")}`,
    );
  });

  test("THE UNION IS WHAT CLOSES THE WINDOW, in both directions", () => {
    // The capability #11042 added, proven rather than assumed: the repo cannot
    // grow a table that this census cannot see, whichever half knows about it
    // first. Driven with synthetic inputs because every real migration table is
    // also live today -- so the interesting case cannot be reached from the
    // repo's own state, which is exactly why it went unnoticed twice.
    const live = "CREATE TABLE public.already_live (\n";
    assert.deepEqual(
      [...tableCensus(live, ["brand_new"])].sort(),
      ["already_live", "brand_new"],
      "a table only its migration knows about must still be classifiable",
    );
    // ...and a census built from nothing is empty rather than universally
    // permissive, so a broken parse fails the size guard above instead of
    // passing this file on an empty comparison.
    assert.equal(tableCensus("", []).size, 0);
  });

  test("the map names no table that does not exist", () => {
    // A stale entry would be swept forever against a dropped table, which
    // fails every batch it lands in and hides the tables beside it.
    //
    // Reads the same union, so classifying a table in the commit that declares
    // it is allowed -- which is the whole point of #11042 -- while classifying
    // one nothing has ever declared still fails.
    const declared = neonTables();
    for (const table of Object.keys(TABLE_FRESHNESS)) {
      assert.ok(
        declared.has(table),
        `${table} is classified but never created`,
      );
    }
  });

  test("every swept column exists on its table (#9866)", () => {
    // THE GAP THAT LET TWELVE THROUGH. The check above asserts the map names
    // no missing TABLE; nothing checked the COLUMN. Eleven entries named a
    // column their table does not have -- chain_detail_* and blocks_head and
    // tao_usd_index carry `observed_at` not `captured_at`, the registry
    // cluster carries `updated_at`, surface_status carries `updated_at` not
    // `checked_at` -- and every one of them threw its whole batch.
    //
    // Reads tests/fixtures/sqlite-schema, which is the same source as the table check and
    // needs no credentials. It cannot see a migration that was never APPLIED
    // (raw_capture_state_v2, #9867) -- that is a different problem, and the
    // reason that entry is excluded with column: "" rather than corrected.
    const dir = path.join(process.cwd(), "tests/fixtures/sqlite-schema");
    const columns = new Map<string, Set<string>>();
    for (const file of readdirSync(dir).filter((f) => f.endsWith(".sql"))) {
      const sql = readFileSync(path.join(dir, file), "utf8");
      for (const m of sql.matchAll(
        /CREATE TABLE\s+(?:IF NOT EXISTS\s+)?(\w+)\s*\(([\s\S]*?)\n\s*\);/gi,
      )) {
        const table = m[1];
        // Strip line comments FIRST: they contain commas, and splitting on
        // those turns a comment word into a phantom column name.
        const body = m[2].replace(/--[^\n]*/g, "");
        const names = new Set<string>(columns.get(table) ?? []);
        let depth = 0;
        let cur = "";
        for (const ch of body) {
          if (ch === "(") depth += 1;
          if (ch === ")") depth -= 1;
          if (ch === "," && depth === 0) {
            cur = "";
            continue;
          }
          cur += ch;
          if (cur.trim().split(/\s+/).length === 1) continue;
          const first = cur.trim().split(/\s+/)[0];
          if (!/^(PRIMARY|UNIQUE|FOREIGN|CHECK|CONSTRAINT)$/i.test(first)) {
            names.add(first.replace(/^["`[]|["`\]]$/g, ""));
          }
        }
        columns.set(table, names);
      }
      // ALTER TABLE ... ADD COLUMN is how several of these arrived.
      for (const m of sql.matchAll(
        /ALTER TABLE\s+(\w+)\s+ADD COLUMN\s+(\w+)/gi,
      )) {
        const set = columns.get(m[1]) ?? new Set<string>();
        set.add(m[2]);
        columns.set(m[1], set);
      }
    }
    const missing: string[] = [];
    for (const [table, e] of Object.entries(TABLE_FRESHNESS)) {
      if (e.column === "") continue;
      const known = columns.get(table);
      if (!known || known.size === 0) continue; // table check owns that case
      if (!known.has(e.column)) {
        missing.push(
          `${table}.${e.column} (has: ${[...known].sort().join(", ")})`,
        );
      }
    }
    assert.deepEqual(
      missing,
      [],
      `a swept column does not exist, so its whole batch throws:\n  ${missing.join("\n  ")}`,
    );
  });

  test("every entry gives a reason, and a threshold or an explicit null", () => {
    for (const [table, e] of Object.entries(TABLE_FRESHNESS)) {
      assert.ok(e.reason.length > 8, `${table} has no real reason`);
      assert.ok(
        e.maxAgeMs === null || e.maxAgeMs > 0,
        `${table}'s maxAgeMs must be a positive number or null`,
      );
      if (e.column === "") {
        assert.equal(
          e.maxAgeMs,
          null,
          `${table} has no timestamp column, so it cannot have a threshold`,
        );
      }
    }
  });

  // WHAT REPLACED "the registry cluster is NOT exempted" (#10657).
  //
  // That test required these three to keep a time bound, because #9779 was a
  // live outage and classifying them `null` to keep the lane green is exactly
  // what a watchdog must never do. Both halves of its premise have since
  // changed: #9779 is closed completed (2026-08-08), and its own closing ask --
  // a lane_health lane for the cluster -- was built. The 48h bound meanwhile
  // measured time since the last registry CHANGE, so a quiet registry breached
  // it with nothing wrong.
  //
  // The protection has to survive that, or this is just the exemption the old
  // test forbade with a nicer comment. So the invariant moves rather than
  // disappearing: a registry-cluster table may drop its bound ONLY by naming
  // the lane that answers the question instead, and that name is checked
  // against the producer's own exported constant -- not a string literal that
  // could rot the way `knownIssue: "#9779"` did.
  test("the registry cluster names its covering lane instead of a bound", () => {
    for (const table of [
      "subnets",
      "surfaces",
      "providers",
      "surface_history",
    ]) {
      const e = TABLE_FRESHNESS[table];
      assert.equal(
        e.maxAgeMs,
        null,
        `${table}: a change-driven producer cannot carry a time bound`,
      );
      assert.equal(
        e.coveredBy,
        REGISTRY_SYNC_LANE,
        `${table} must name the lane that carries its liveness`,
      );
      // The dead citation this issue was about. #9779 is closed; pointing at it
      // sent readers to a completed fix with no explanation for 57.2h.
      assert.equal(
        e.knownIssue,
        undefined,
        `${table} should not cite a closed issue`,
      );
    }
  });

  test("no table drops its bound without naming a covering lane", () => {
    // The general form, so a future `maxAgeMs: null` cannot quietly mean
    // "silenced". Either staleness is genuinely meaningless here -- the
    // signup-driven and append-on-change tables, which say so in `reason` --
    // or something else is watching and this says which.
    for (const [table, e] of Object.entries(TABLE_FRESHNESS)) {
      if (e.coveredBy === undefined) continue;
      assert.equal(
        e.maxAgeMs,
        null,
        `${table}: coveredBy is only meaningful without a bound`,
      );
      assert.ok(
        e.reason.length > 0,
        `${table}: a redirected table still owes a reason`,
      );
    }
  });
});

describe("freshnessSql", () => {
  test("asks a batch in one statement", () => {
    // Two tables that read themselves, so this stays a test about BATCHING.
    // The redirect has its own tests below.
    assert.equal(
      freshnessSql(["tao_usd_index", "lane_health"]),
      "SELECT 'tao_usd_index' AS t, MAX(observed_at) AS mx FROM tao_usd_index UNION ALL " +
        "SELECT 'lane_health' AS t, MAX(checked_at) AS mx FROM lane_health",
    );
  });

  test("a stampFrom entry reads its companion but keeps its own label", () => {
    // The label is what every downstream map keys on -- staleTables, the
    // verdict and the alarm text all look up `neurons`. Only the FROM moves.
    assert.equal(
      freshnessSql(["neurons"]),
      "SELECT 'neurons' AS t, MAX(captured_at) AS mx FROM neurons_passes",
    );
  });

  test("the metagraph family all redirect to the one pass table", () => {
    // One 15-minute pass writes all three from the same clock read, so three
    // scans of 19 MB + 486 MB + 497 MB collapse to one read of 88 kB.
    for (const t of ["neurons", "neuron_daily", "account_position_daily"]) {
      assert.match(
        freshnessSql([t]),
        /FROM neurons_passes$/,
        `${t} should read the pass table`,
      );
    }
  });

  test("every stampFrom names a table that is itself swept", () => {
    // A redirect target that nothing watches would be a blind spot one level
    // down: the sweep would trust a stamp from a table it never checks.
    const swept = new Set(freshnessTables());
    for (const [table, entry] of Object.entries(TABLE_FRESHNESS)) {
      if (!entry.stampFrom) continue;
      assert.ok(
        swept.has(entry.stampFrom),
        `${table} redirects to ${entry.stampFrom}, which is not swept itself`,
      );
    }
  });

  test("the cross-check asks for both numbers, per redirected table", () => {
    const spec: Record<string, FreshnessExpectation> = {
      big: {
        column: "captured_at",
        kind: "ms",
        maxAgeMs: HOUR,
        reason: "x",
        stampFrom: "big_passes",
      },
      plain: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "y" },
    };
    assert.equal(
      crossCheckSql(spec),
      "SELECT 'big' AS t, (SELECT MAX(captured_at) FROM big_passes) AS cheap, " +
        "(SELECT MAX(captured_at) FROM big) AS actual",
    );
  });

  test("a table with no stampFrom is not cross-checked", () => {
    // It reads itself, so there is nothing to disagree with.
    const spec: Record<string, FreshnessExpectation> = {
      plain: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "y" },
    };
    assert.equal(crossCheckSql(spec), "");
  });

  test("batches stay under D1's compound-SELECT term limit", () => {
    // D1 rejected a compound SELECT past roughly five terms.
    assert.ok(FRESHNESS_BATCH <= 4, "batch size must keep a margin under 5");
  });

  test("only tables with a column are swept", () => {
    const swept = freshnessTables();
    assert.ok(!swept.includes("api_key_blocks"), "no timestamp column");
    assert.ok(swept.includes("neurons"));
  });
});

describe("stampDivergences", () => {
  const spec: Record<string, FreshnessExpectation> = {
    big: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: HOUR,
      reason: "x",
      stampFrom: "big_passes",
    },
    plain: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "y" },
  };

  test("agreement is silence", () => {
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: 1000, actual: 1000 }], spec),
      [],
    );
  });

  test("a disagreement carries BOTH numbers, not a boolean", () => {
    // Whoever reads the alarm needs to know which way it drifted and by how
    // much -- "they disagree" is not actionable on its own.
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: 2000, actual: 1000 }], spec),
      [{ table: "big", stampFrom: "big_passes", cheap: 2000, actual: 1000 }],
    );
  });

  test("the LAG direction is expected, not a divergence (#10656)", () => {
    // The pass row lands after the rows it counts, so a cheap stamp that
    // trails is the writes being ordered. Demanding equality made that
    // indistinguishable from a fault and pinned the lane at `unknown` --
    // measured at 75 minutes on 2026-08-11. `confirmRedirectedStale` is what
    // stops the lag costing a false alarm instead.
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: 1000, actual: 2000 }], spec),
      [],
    );
  });

  test("a cheap stamp RUNNING AHEAD is still reported -- that is #9530", () => {
    // The genuinely alarming direction: the pass row claims data the table
    // does not hold, which is a freshness signal advancing over data that has
    // not arrived.
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: 2000, actual: 1999 }], spec),
      [{ table: "big", stampFrom: "big_passes", cheap: 2000, actual: 1999 }],
    );
  });

  test("an empty pass table beside a populated one IS a divergence", () => {
    // This is the redirect reading nothing at all -- the failure the
    // cross-check exists for. Skipping nulls would make it look healthy.
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: null, actual: 1000 }], spec),
      [{ table: "big", stampFrom: "big_passes", cheap: null, actual: 1000 }],
    );
  });

  test("both empty is a table nothing has written yet, not a divergence", () => {
    assert.deepEqual(
      stampDivergences([{ t: "big", cheap: null, actual: null }], spec),
      [],
    );
  });

  test("a row for a table with no stampFrom is ignored", () => {
    assert.deepEqual(
      stampDivergences([{ t: "plain", cheap: 1, actual: 2 }], spec),
      [],
    );
  });

  test("a row with no table name is ignored rather than crashed on", () => {
    // A store that answers without the label column must not take the sweep
    // down with it -- the freshness result beside it is still real.
    assert.deepEqual(stampDivergences([{ cheap: 1, actual: 2 }], spec), []);
  });
});

describe("crossCheckStamps", () => {
  const redirected: Record<string, FreshnessExpectation> = {
    big: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: HOUR,
      reason: "x",
      stampFrom: "big_passes",
    },
  };
  const plainOnly: Record<string, FreshnessExpectation> = {
    plain: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "y" },
  };

  test("a spec with no redirects asks nothing and reports no failure", async () => {
    // Nothing to prove is not the same as failing to prove it.
    assert.deepEqual(await crossCheckStamps(null, {}, plainOnly), {
      divergences: [],
      failed: false,
    });
  });

  test("no reachable store is a FAILURE, not a silent pass", async () => {
    // readStore(null, ...) yields no db. The redirect went unverified this
    // tick, which the sweep must escalate rather than absorb.
    assert.deepEqual(await crossCheckStamps(null, {}, redirected), {
      divergences: [],
      failed: true,
    });
  });

  test("zero cross-check rows is agreement, not a crash", async () => {
    // The D1 "no results key" case retired with the envelope (#10909): the
    // owned query() answers rows, so zero rows IS the agreement shape.
    const db = { query: async () => [] };
    assert.deepEqual(
      await crossCheckStamps(null, { db: db as never }, redirected),
      { divergences: [], failed: false },
    );
  });

  test("rows that disagree come back as divergences", async () => {
    const db = { query: async () => [{ t: "big", cheap: 2, actual: 1 }] };
    const out = await crossCheckStamps(null, { db: db as never }, redirected);
    assert.equal(out.failed, false);
    assert.deepEqual(out.divergences, [
      { table: "big", stampFrom: "big_passes", cheap: 2, actual: 1 },
    ]);
  });

  test("a throwing store is a failure, not an exception", async () => {
    const db = {
      query: async (): Promise<never> => {
        throw new Error("store: overloaded");
      },
    };
    assert.deepEqual(
      await crossCheckStamps(null, { db: db as never }, redirected),
      { divergences: [], failed: true },
    );
  });
});

describe("confirmRedirectedStale (#10656)", () => {
  const NOW = 10 * HOUR;
  const spec: Record<string, FreshnessExpectation> = {
    big: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: HOUR,
      reason: "x",
      stampFrom: "big_passes",
    },
    plain: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "y" },
  };
  const staleBig = {
    table: "big",
    ageMs: 2 * HOUR,
    maxAgeMs: HOUR,
    reason: "x",
  };
  const stalePlain = {
    table: "plain",
    ageMs: 2 * HOUR,
    maxAgeMs: HOUR,
    reason: "y",
  };

  /** Answers the confirm's own `{t, mx}` shape. */
  function confirmDb(byTable: Record<string, number | null>, fail = false) {
    return {
      async query(sql: string) {
        if (fail) throw new Error("store: overloaded");
        const names = [...sql.matchAll(/SELECT '(\w+)' AS t/g)].map(
          (m) => m[1],
        );
        return names.map((t) => ({ t, mx: byTable[t as string] ?? null }));
      },
    };
  }

  test("a redirected table whose OWN stamp is fresh is dropped", async () => {
    // The whole point: the pass table trails the data table, so a cheap stamp
    // can read late while the table itself is current. Measured at 75 minutes
    // against a 120-minute bound on 2026-08-11.
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      { db: confirmDb({ big: NOW - HOUR / 2 }) as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, []);
  });

  test("a redirected table that is REALLY stale still reports", async () => {
    // The confirm must not become a way to lose a real outage on the estate's
    // largest tables.
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      { db: confirmDb({ big: NOW - 5 * HOUR }) as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [staleBig]);
  });

  test("a NON-redirected table is never re-asked", async () => {
    // It measured itself; re-asking would be the scan this exists to avoid.
    let asked = 0;
    const db = {
      async query(sql: string) {
        asked += 1;
        return {
          async all() {
            return {
              results: [...sql.matchAll(/SELECT '(\w+)' AS t/g)].map((m) => ({
                t: m[1],
                mx: NOW,
              })),
            };
          },
        };
      },
    };
    const out = await confirmRedirectedStale(
      [stalePlain],
      null,
      { db: db as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [stalePlain]);
    assert.equal(asked, 0, "no confirm query for a table that measured itself");
  });

  test("a FAILED confirm keeps the stale finding", async () => {
    // Nothing refuted the cheap stamp, so dropping it here would be the one
    // way this could hide a real outage.
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      { db: confirmDb({}, true) as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [staleBig]);
  });

  test("no reachable store keeps the finding, resolving its own db", async () => {
    // No injected db and no env: readStore has nothing to open, so the
    // confirm asks nothing and cannot refute the cheap stamp. Same rule as a
    // failed query -- an unproven staleness is still reported.
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      {},
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [staleBig]);
  });

  test("a table with no stamp of its own keeps the finding", async () => {
    // An absence establishes nothing either way.
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      { db: confirmDb({ big: null }) as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [staleBig]);
  });

  test("a mixed list keeps the direct finding while clearing the confirmed one", async () => {
    // The filter runs over the WHOLE list, not just the suspects: a
    // non-redirected table measured itself and must survive a confirm that
    // clears its neighbour.
    const out = await confirmRedirectedStale(
      [staleBig, stalePlain],
      null,
      { db: confirmDb({ big: NOW - HOUR / 2 }) as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [stalePlain]);
  });

  test("a result carrying no rows key keeps the finding", async () => {
    // `result.results ?? []` -- a store that answers with no `results` key at
    // all is not a refutation, and must not be read as an empty confirm that
    // clears the finding.
    const db = {
      prepare() {
        return {
          async all() {
            return {};
          },
        };
      },
    };
    const out = await confirmRedirectedStale(
      [staleBig],
      null,
      { db: db as never },
      () => NOW,
      spec,
    );
    assert.deepEqual(out, [staleBig]);
  });

  test("nothing stale asks nothing at all", async () => {
    let asked = 0;
    const db = {
      prepare() {
        asked += 1;
        return {
          async all() {
            return { results: [] };
          },
        };
      },
    };
    assert.deepEqual(
      await confirmRedirectedStale(
        [],
        null,
        { db: db as never },
        () => NOW,
        spec,
      ),
      [],
    );
    assert.equal(asked, 0);
  });
});

describe("staleTables", () => {
  const spec: Record<string, FreshnessExpectation> = {
    fast: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: HOUR,
      reason: "hourly",
    },
    slow: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: 48 * HOUR,
      reason: "daily",
    },
    never: {
      column: "created_at",
      kind: "ms",
      maxAgeMs: null,
      reason: "signup",
    },
  };

  test("reports only tables past their OWN threshold, worst first", () => {
    const out = staleTables(
      new Map([
        ["fast", NOW - 5 * HOUR],
        ["slow", NOW - 5 * HOUR],
        ["never", NOW - 900 * HOUR],
      ]),
      NOW,
      spec,
    );
    assert.deepEqual(
      out.map((s) => s.table),
      ["fast"],
    );
    assert.equal(out[0].maxAgeMs, HOUR);
  });

  test("a null threshold is never stale, however old", () => {
    assert.deepEqual(staleTables(new Map([["never", 0]]), NOW, spec), []);
  });

  test("an EMPTY table is not stale", () => {
    // No arrival means nothing is late. Reporting it would make every
    // not-yet-populated table permanently loud.
    assert.deepEqual(staleTables(new Map(), NOW, spec), []);
  });

  test("exactly at the threshold is not stale", () => {
    assert.deepEqual(
      staleTables(new Map([["fast", NOW - HOUR]]), NOW, spec),
      [],
    );
  });
});

describe("parseFreshnessRows", () => {
  const spec: Record<string, FreshnessExpectation> = {
    ms: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "x" },
    dated: { column: "day", kind: "date", maxAgeMs: HOUR, reason: "x" },
  };

  test("reads epoch-ms and date columns alike", () => {
    const out = parseFreshnessRows(
      [
        { t: "ms", mx: NOW },
        { t: "dated", mx: "2026-08-07" },
      ],
      spec,
    );
    assert.equal(out.get("ms"), NOW);
    assert.equal(out.get("dated"), Date.parse("2026-08-07T00:00:00Z"));
  });

  test("a NULL max is dropped, not read as 1970", () => {
    // `Number(null)` is 0 and passes Number.isFinite. Reading MAX() over an
    // empty table as epoch 0 would report it as decades stale.
    assert.equal(parseFreshnessRows([{ t: "ms", mx: null }], spec).size, 0);
    assert.equal(parseFreshnessRows([{ t: null, mx: NOW }], spec).size, 0);
    assert.equal(parseFreshnessRows([{ t: "ms", mx: "nope" }], spec).size, 0);
  });

  test("a table the spec does not know is ignored", () => {
    assert.equal(
      parseFreshnessRows([{ t: "surprise", mx: NOW }], spec).size,
      0,
    );
  });
});

describe("describeStaleTables", () => {
  test("names the age, the cap, and any known issue", () => {
    assert.equal(
      describeStaleTables([]),
      "every table is within its expected age",
    );
    assert.equal(
      describeStaleTables([
        {
          table: "surfaces",
          ageMs: 126 * HOUR,
          maxAgeMs: 48 * HOUR,
          reason: "x",
          knownIssue: "#9779",
        },
        { table: "neurons", ageMs: 3 * HOUR, maxAgeMs: 2 * HOUR, reason: "y" },
      ]),
      "surfaces 126.0h > 48h (known: #9779); neurons 3.0h > 2h",
    );
  });
});

describe("runTableFreshnessWatchdog", () => {
  const spec: Record<string, FreshnessExpectation> = {
    a: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "hourly" },
    b: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "hourly" },
    c: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "hourly" },
    d: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "hourly" },
    e: { column: "captured_at", kind: "ms", maxAgeMs: HOUR, reason: "hourly" },
    skip: { column: "", kind: "ms", maxAgeMs: null, reason: "no column" },
  };
  const fresh = { a: NOW, b: NOW, c: NOW, d: NOW, e: NOW };

  // --- the stampFrom cross-check ----------------------------------------
  //
  // The redirect is only sound while the pass stamp equals the table's own, so
  // these cover the three outcomes of proving it: agree, disagree, unaskable.
  const redirectSpec: Record<string, FreshnessExpectation> = {
    big: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: 8 * HOUR,
      reason: "redirected",
      stampFrom: "big_passes",
    },
    big_passes: {
      column: "captured_at",
      kind: "ms",
      maxAgeMs: 8 * HOUR,
      reason: "the pass table itself",
    },
  };

  test("agreement leaves the verdict alone", async () => {
    const spy = fakeDb({ big: NOW, big_passes: NOW }, [], {
      big: { cheap: NOW, actual: NOW },
    });
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec: redirectSpec,
    });
    assert.deepEqual(out.divergences, []);
    assert.equal(spy.written[0].verdict, "ok");
    assert.ok(!String(spy.written[0].detail).includes("stampFrom"));
  });

  test("a divergence is UNKNOWN, not stale, and names both numbers", async () => {
    // The data may be perfectly fresh -- what failed is the measurement. Saying
    // "stale" would report an outage that may not exist.
    const spy = fakeDb({ big: NOW, big_passes: NOW }, [], {
      big: { cheap: NOW, actual: NOW - 5 * HOUR },
    });
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec: redirectSpec,
    });
    assert.equal(out.divergences?.length, 1);
    assert.equal(spy.written[0].verdict, "unknown");
    const detail = String(spy.written[0].detail);
    assert.ok(detail.includes("stampFrom DIVERGED"), detail);
    assert.ok(detail.includes(String(NOW)), detail);
    assert.ok(detail.includes(String(NOW - 5 * HOUR)), detail);
  });

  test("an unaskable cross-check is UNKNOWN and says so distinctly", async () => {
    // "they disagree" and "we could not ask" are different findings, and the
    // detail has to tell them apart or the alarm points nowhere.
    const spy = fakeDb({ big: NOW, big_passes: NOW }, ["AS cheap"]);
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec: redirectSpec,
    });
    assert.deepEqual(out.divergences, []);
    assert.equal(spy.written[0].verdict, "unknown");
    const detail = String(spy.written[0].detail);
    assert.ok(detail.includes("cross-check unreadable"), detail);
    assert.ok(!detail.includes("DIVERGED"), detail);
  });

  test("a spec with no redirects never issues a cross-check", async () => {
    const spy = fakeDb(fresh);
    await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.ok(
      !spy.calls.some((c) => c.includes("AS cheap")),
      "nothing to cross-check, so nothing should be asked",
    );
  });

  test("records OK when every table is within its age", async () => {
    const spy = fakeDb(fresh);
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.deepEqual(out.stale, []);
    assert.equal(out.checked, 5);
    assert.equal(spy.written[0].lane, TABLE_FRESHNESS_LANE);
    assert.equal(spy.written[0].verdict, "ok");
  });

  test("batches rather than issuing one huge compound SELECT", async () => {
    const spy = fakeDb(fresh);
    await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    const selects = spy.calls.filter((c) => c.startsWith("SELECT"));
    assert.equal(selects.length, 2, "5 tables at batch size 4 = 2 batches");
    for (const s of selects) {
      assert.ok(
        (s.match(/UNION ALL/g) ?? []).length < 4,
        `batch has too many terms: ${s}`,
      );
    }
    // The column-less table is never queried.
    assert.ok(!selects.some((s) => s.includes("'skip'")));
  });

  test("records STALE with the worst age", async () => {
    const spy = fakeDb({ ...fresh, a: NOW - 9 * HOUR, b: NOW - 3 * HOUR });
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.deepEqual(
      out.stale?.map((s) => s.table),
      ["a", "b"],
    );
    assert.equal(spy.written[0].verdict, "stale");
    assert.equal(spy.written[0].age, 9 * HOUR);
  });

  test("ONE bad table costs ONLY itself, not the three beside it (#9866)", async () => {
    // a/b/c/d share a batch (FRESHNESS_BATCH = 4) and the stub fails any SQL
    // naming 'a'. The batch UNION therefore throws -- and used to take b, c
    // and d down with it, which is how 12 bad entries blinded 7 of 12 batches
    // and 58% of the estate. The retry reads them individually.
    const spy = fakeDb({ ...fresh, e: NOW - 9 * HOUR }, ["'a'"]);
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.equal(
      out.checked,
      4,
      "b, c and d must survive their batch-mate; e comes from its own batch",
    );
    assert.deepEqual(
      out.stale?.map((s) => s.table),
      ["e"],
    );
    // Names the table, not a batch count -- "7 of 12 batches unreadable" gave
    // nobody anything to go and fix.
    assert.match(String(spy.written[0].detail), /1 unreadable: a/);
  });

  test("an unreadable table makes the verdict unknown, never ok (#9866)", async () => {
    // THE BUG: `failed` reached the detail STRING and never the verdict, so a
    // sweep that read 5 of 12 batches still published `ok` -- and lane-alarm
    // keys on the verdict, so nothing fired.
    const spy = fakeDb(fresh, ["'a'"]);
    await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.equal(
      spy.written[0].verdict,
      "unknown",
      "nothing measured is stale, but the sweep did not establish that every " +
        "table is fresh — `ok` is the one answer that cannot be right",
    );
    assert.match(String(spy.written[0].detail), /1 unreadable: a/);
  });

  test("a stale finding outranks an incomplete sweep", async () => {
    // A real breach is information; report it rather than downgrading to
    // unknown because some other table could not be read.
    const spy = fakeDb({ ...fresh, e: NOW - 9 * HOUR }, ["'a'"]);
    await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.equal(spy.written[0].verdict, "stale");
  });

  test("a complete sweep that measured NOTHING is not ok either", async () => {
    // D1 can answer without a `results` key; the `?? []` absorbs it rather
    // than throwing. Absorbing the crash must not also manufacture a green.
    const empty = fakeDb({});
    await runTableFreshnessWatchdog(null, {
      db: empty.db,
      laneHealthDb: empty.db,
      now: () => NOW,
      spec,
    });
    assert.equal(empty.written[0].verdict, "unknown");
  });

  test("EVERY batch failing is unknown, never ok", async () => {
    // "nothing was measured" and "nothing is stale" must not look alike.
    const spy = fakeDb(fresh, ["SELECT"]);
    const out = await runTableFreshnessWatchdog(null, {
      db: spy.db,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.equal(out.reason, "all batches failed");
    assert.equal(spy.written[0].verdict, "unknown");
  });

  test("an unbound D1 is unknown too", async () => {
    const spy = fakeDb({});
    const out = await runTableFreshnessWatchdog(null, {
      db: null,
      laneHealthDb: spy.db,
      now: () => NOW,
      spec,
    });
    assert.equal(out.reason, "all batches failed");
    assert.equal(spy.written[0].verdict, "unknown");
  });

  test("a batch answering zero rows contributes nothing, not a crash", async () => {
    // The D1 "no results key" premise retired with the envelope (#10909):
    // zero rows is the one nothing-shape the owned store can produce.
    const noKey = {
      query: async () => [],
      run: async () => ({ changes: 1 }),
    };
    const out = await runTableFreshnessWatchdog(null, {
      db: noKey,
      laneHealthDb: noKey,
      now: () => NOW,
      spec,
    });
    assert.equal(out.checked, 0);
    assert.deepEqual(out.stale, []);
  });

  test("takes its D1 and clock off env with no deps", async () => {
    const spy = fakeDb({});
    const out = await runTableFreshnessWatchdog({
      METAGRAPH_HEALTH_DB: spy.db,
    });
    assert.equal(out.attempted, true);
  });
});

describe("the deployed wiring", () => {
  const wrangler = readFileSync("wrangler.data.jsonc", "utf8");

  test("the cron the handler dispatches on is declared", async () => {
    const { TABLE_FRESHNESS_CRON } = await import("../workers/config.ts");
    assert.ok(
      wrangler.includes(`"${TABLE_FRESHNESS_CRON}"`),
      `wrangler.data.jsonc declares no "${TABLE_FRESHNESS_CRON}" cron, so the sweep never runs`,
    );
  });

  test("the cadence is faster than the tightest threshold it enforces", async () => {
    // A sweep slower than what it checks would report a breach late enough to
    // be useless. Hourly against a two-hour floor leaves one tick of margin.
    const { TABLE_FRESHNESS_CRON } = await import("../workers/config.ts");
    assert.match(
      TABLE_FRESHNESS_CRON,
      /^\d+ \* \* \* \*$/,
      "expected an hourly cron",
    );
    const tightest = Math.min(
      ...Object.values(TABLE_FRESHNESS)
        .map((e) => e.maxAgeMs)
        .filter((v): v is number => v != null),
    );
    assert.ok(
      tightest >= 2 * HOUR,
      `tightest threshold is ${tightest / HOUR}h but the sweep runs hourly -- ` +
        `anything under 2h would alarm on its own sampling gap`,
    );
  });
});
