-- Provenance for the v440 emission-pipeline columns (#8744).
--
-- 0050 stored the pipeline INPUTS but not the height they were read at, and
-- #8744 makes the decomposition built from them a published surface. That
-- decomposition is our arithmetic over chain measurements (ADR 0023 decision
-- 3); a reader who cannot tell which block the inputs came from cannot check
-- our work, which ADR 0023 decision 5 says is not optional.
--
-- The height was never missing from the pipeline -- fetch-native-subnets.py
-- has emitted chain_state.block/block_hash since #8743, pinning every read in
-- a tick to ONE block precisely so the terms could not be added across
-- different instants. It was simply dropped on the way into the artifact.
--
-- PER-ROW, THOUGH THE VALUE IS NETWORK-WIDE. One state_queryStorageAt produced
-- the whole network's inputs, so every row of a given capture carries the same
-- height, and a separate captures table keyed by snapshot_date would be the
-- normalized form. Per-row wins anyway: provenance that travels with the value
-- cannot be silently joined to the wrong capture, and a degraded refresh --
-- where some subnets have pipeline inputs and others do not -- stays
-- self-describing row by row rather than claiming a height for rows that have
-- no pinned reads behind them.
--
-- NULL means "no pinned read behind this row's pipeline columns". It is never
-- backfilled from captured_at or from chain tip: a height nothing was read at
-- is worse than no height, because it looks like provenance.
--
-- No issuance column, deliberately. Block emission is a step function of
-- issuance (#8747) that only moves at a halving, and
-- emission_gate_param_history already records block_emission_halvings against
-- block_number -- as it does theta, q and h. The value in force at
-- pipeline_block is therefore a lookup against history, not a fact to
-- duplicate across 128 rows a day.
--
-- subnet_snapshots predates the migration directory -- its DDL lives in
-- deploy/postgres/schema.sql, which only ever runs against a fresh database.
-- The live box needs this ALTER to see the columns at all.
ALTER TABLE subnet_snapshots
  ADD COLUMN IF NOT EXISTS pipeline_block      BIGINT,
  -- The hash, not just the height: a height alone is ambiguous across a reorg,
  -- and re-verifying a published decomposition means replaying the exact state
  -- the reads saw.
  ADD COLUMN IF NOT EXISTS pipeline_block_hash TEXT;
