// GENERATED by scripts/generate-lakehouse-types.ts from
// generated/lakehouse/schema.json. Do not edit. Run `npm run build:lakehouse-types`
// after re-snapshotting the catalog with `npm run refresh:lakehouse-schema`.
//
// One Zod schema per Iceberg table in the `chain` namespace -- the runtime
// half of types.ts. A read validates against these; it does not cast to
// them.

import { z } from "zod";

/**
 * `chain.blocks` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const BlocksRowSchema = z
  .object({
    block_number: z.int().nullable(),
    block_hash: z.string().nullable(),
    parent_hash: z.string().nullable(),
    author: z.string().nullable(),
    extrinsic_count: z.int().nullable(),
    event_count: z.int().nullable(),
    spec_version: z.int().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.extrinsics` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const ExtrinsicsRowSchema = z
  .object({
    block_number: z.int().nullable(),
    extrinsic_index: z.int().nullable(),
    extrinsic_hash: z.string().nullable(),
    signer: z.string().nullable(),
    call_module: z.string().nullable(),
    call_function: z.string().nullable(),
    success: z.boolean().nullable(),
    fee_tao: z.number().nullable(),
    tip_tao: z.number().nullable(),
    call_args: z.string().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.chain_events` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const ChainEventsRowSchema = z
  .object({
    block_number: z.int().nullable(),
    event_index: z.int().nullable(),
    pallet: z.string().nullable(),
    method: z.string().nullable(),
    args: z.string().nullable(),
    phase: z.string().nullable(),
    extrinsic_index: z.int().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.account_events` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const AccountEventsRowSchema = z
  .object({
    block_number: z.int().nullable(),
    event_index: z.int().nullable(),
    extrinsic_index: z.int().nullable(),
    event_kind: z.string().nullable(),
    hotkey: z.string().nullable(),
    coldkey: z.string().nullable(),
    netuid: z.int().nullable(),
    uid: z.int().nullable(),
    amount_tao: z.number().nullable(),
    alpha_amount: z.number().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.account_identity` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const AccountIdentityRowSchema = z
  .object({
    account: z.string().nullable(),
    name: z.string().nullable(),
    url: z.string().nullable(),
    github: z.string().nullable(),
    image: z.string().nullable(),
    discord: z.string().nullable(),
    description: z.string().nullable(),
    additional: z.string().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.account_identity_history` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const AccountIdentityHistoryRowSchema = z
  .object({
    id: z.int().nullable(),
    account: z.string().nullable(),
    observed_at: z.int().nullable(),
    name: z.string().nullable(),
    url: z.string().nullable(),
    github: z.string().nullable(),
    image: z.string().nullable(),
    discord: z.string().nullable(),
    description: z.string().nullable(),
    additional: z.string().nullable(),
    identity_hash: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.nominator_positions` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const NominatorPositionsRowSchema = z
  .object({
    coldkey: z.string().nullable(),
    hotkey: z.string().nullable(),
    netuid: z.int().nullable(),
    share_fraction: z.number().nullable(),
    captured_at: z.int().nullable(),
    shares: z.number().nullable(),
    source: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.rpc_proxy_events` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const RpcProxyEventsRowSchema = z
  .object({
    id: z.int().nullable(),
    observed_at: z.int().nullable(),
    network: z.string().nullable(),
    endpoint_id: z.string().nullable(),
    provider: z.string().nullable(),
    ok: z.boolean().nullable(),
    status: z.int().nullable(),
    attempts: z.int().nullable(),
    latency_ms: z.int().nullable(),
    cache: z.string().nullable(),
    sample_interval: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.self_health_daily` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SelfHealthDailyRowSchema = z
  .object({
    day: z.iso.date().nullable(),
    component: z.string().nullable(),
    checks: z.int().nullable(),
    ok_count: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_hyperparams` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetHyperparamsRowSchema = z
  .object({
    netuid: z.int().nullable(),
    kappa_ratio: z.number().nullable(),
    immunity_period: z.int().nullable(),
    min_allowed_weights: z.int().nullable(),
    max_weight_limit_ratio: z.number().nullable(),
    tempo: z.int().nullable(),
    weights_version: z.int().nullable(),
    weights_rate_limit: z.number().nullable(),
    activity_cutoff: z.int().nullable(),
    activity_cutoff_factor: z.int().nullable(),
    registration_allowed: z.boolean().nullable(),
    target_regs_per_interval: z.int().nullable(),
    min_burn_tao: z.number().nullable(),
    max_burn_tao: z.number().nullable(),
    burn_half_life: z.int().nullable(),
    burn_increase_mult: z.number().nullable(),
    bonds_moving_avg_raw: z.int().nullable(),
    max_regs_per_block: z.int().nullable(),
    serving_rate_limit: z.int().nullable(),
    max_validators: z.int().nullable(),
    commit_reveal_period: z.int().nullable(),
    commit_reveal_enabled: z.boolean().nullable(),
    alpha_high_ratio: z.number().nullable(),
    alpha_low_ratio: z.number().nullable(),
    liquid_alpha_enabled: z.boolean().nullable(),
    alpha_sigmoid_steepness: z.number().nullable(),
    yuma_version: z.int().nullable(),
    subnet_is_active: z.boolean().nullable(),
    transfers_enabled: z.boolean().nullable(),
    bonds_reset_enabled: z.boolean().nullable(),
    user_liquidity_enabled: z.boolean().nullable(),
    owner_cut_enabled: z.boolean().nullable(),
    owner_cut_auto_lock_enabled: z.boolean().nullable(),
    min_childkey_take_ratio: z.number().nullable(),
    block_number: z.int().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_hyperparams_history` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetHyperparamsHistoryRowSchema = z
  .object({
    id: z.int().nullable(),
    netuid: z.int().nullable(),
    block_number: z.int().nullable(),
    observed_at: z.int().nullable(),
    kappa_ratio: z.number().nullable(),
    immunity_period: z.int().nullable(),
    min_allowed_weights: z.int().nullable(),
    max_weight_limit_ratio: z.number().nullable(),
    tempo: z.int().nullable(),
    weights_version: z.int().nullable(),
    weights_rate_limit: z.number().nullable(),
    activity_cutoff: z.int().nullable(),
    activity_cutoff_factor: z.int().nullable(),
    registration_allowed: z.boolean().nullable(),
    target_regs_per_interval: z.int().nullable(),
    min_burn_tao: z.number().nullable(),
    max_burn_tao: z.number().nullable(),
    burn_half_life: z.int().nullable(),
    burn_increase_mult: z.number().nullable(),
    bonds_moving_avg_raw: z.int().nullable(),
    max_regs_per_block: z.int().nullable(),
    serving_rate_limit: z.int().nullable(),
    max_validators: z.int().nullable(),
    commit_reveal_period: z.int().nullable(),
    commit_reveal_enabled: z.boolean().nullable(),
    alpha_high_ratio: z.number().nullable(),
    alpha_low_ratio: z.number().nullable(),
    liquid_alpha_enabled: z.boolean().nullable(),
    alpha_sigmoid_steepness: z.number().nullable(),
    yuma_version: z.int().nullable(),
    subnet_is_active: z.boolean().nullable(),
    transfers_enabled: z.boolean().nullable(),
    bonds_reset_enabled: z.boolean().nullable(),
    user_liquidity_enabled: z.boolean().nullable(),
    owner_cut_enabled: z.boolean().nullable(),
    owner_cut_auto_lock_enabled: z.boolean().nullable(),
    min_childkey_take_ratio: z.number().nullable(),
    hyperparams_hash: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_identity_history` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetIdentityHistoryRowSchema = z
  .object({
    id: z.int().nullable(),
    netuid: z.int().nullable(),
    block_number: z.int().nullable(),
    observed_at: z.int().nullable(),
    subnet_name: z.string().nullable(),
    symbol: z.string().nullable(),
    description: z.string().nullable(),
    github_repo: z.string().nullable(),
    subnet_url: z.string().nullable(),
    discord: z.string().nullable(),
    logo_url: z.string().nullable(),
    identity_hash: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_ownership_history` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetOwnershipHistoryRowSchema = z
  .object({
    id: z.int().nullable(),
    netuid: z.int().nullable(),
    owner_hotkey: z.string().nullable(),
    owner_coldkey: z.string().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.neuron_daily` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const NeuronDailyRowSchema = z
  .object({
    netuid: z.int().nullable(),
    uid: z.int().nullable(),
    snapshot_date: z.iso.date().nullable(),
    hotkey: z.string().nullable(),
    coldkey: z.string().nullable(),
    active: z.boolean().nullable(),
    validator_permit: z.boolean().nullable(),
    rank: z.number().nullable(),
    trust: z.number().nullable(),
    validator_trust: z.number().nullable(),
    consensus: z.number().nullable(),
    incentive: z.number().nullable(),
    dividends: z.number().nullable(),
    emission_tao: z.number().nullable(),
    stake_tao: z.number().nullable(),
    registered_at_block: z.int().nullable(),
    is_immunity_period: z.boolean().nullable(),
    axon: z.string().nullable(),
    block_number: z.int().nullable(),
    captured_at: z.int().nullable(),
    updated_at: z.int().nullable(),
    take: z.number().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.account_position_daily` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const AccountPositionDailyRowSchema = z
  .object({
    account: z.string().nullable(),
    netuid: z.int().nullable(),
    snapshot_date: z.iso.date().nullable(),
    uid: z.int().nullable(),
    coldkey: z.string().nullable(),
    active: z.boolean().nullable(),
    validator_permit: z.boolean().nullable(),
    rank: z.number().nullable(),
    trust: z.number().nullable(),
    incentive: z.number().nullable(),
    dividends: z.number().nullable(),
    stake_tao: z.number().nullable(),
    emission_tao: z.number().nullable(),
    captured_at: z.int().nullable(),
    updated_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_snapshots` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetSnapshotsRowSchema = z
  .object({
    netuid: z.int().nullable(),
    snapshot_date: z.iso.date().nullable(),
    completeness_score: z.int().nullable(),
    surface_count: z.int().nullable(),
    endpoint_count: z.int().nullable(),
    monitored_count: z.int().nullable(),
    candidate_count: z.int().nullable(),
    captured_at: z.int().nullable(),
    validator_count: z.int().nullable(),
    miner_count: z.int().nullable(),
    total_stake_tao: z.number().nullable(),
    alpha_price_tao: z.number().nullable(),
    emission_share: z.number().nullable(),
    tao_in_pool_tao: z.number().nullable(),
    alpha_in_pool: z.number().nullable(),
    alpha_out_pool: z.number().nullable(),
    subnet_volume_tao: z.number().nullable(),
    tao_in_emission_tao: z.number().nullable(),
    excess_tao: z.number().nullable(),
    alpha_in_emission: z.number().nullable(),
    alpha_out_emission: z.number().nullable(),
    miner_burned_fraction: z.number().nullable(),
    emission_enabled: z.boolean().nullable(),
    subtoken_enabled: z.boolean().nullable(),
    first_emission_block: z.int().nullable(),
    pipeline_block: z.int().nullable(),
    pipeline_block_hash: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.account_balances` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const AccountBalancesRowSchema = z
  .object({
    ss58: z.string().nullable(),
    free_tao: z.number().nullable(),
    reserved_tao: z.number().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.neurons` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const NeuronsRowSchema = z
  .object({
    netuid: z.int().nullable(),
    uid: z.int().nullable(),
    hotkey: z.string().nullable(),
    coldkey: z.string().nullable(),
    active: z.boolean().nullable(),
    validator_permit: z.boolean().nullable(),
    rank: z.number().nullable(),
    trust: z.number().nullable(),
    validator_trust: z.number().nullable(),
    consensus: z.number().nullable(),
    incentive: z.number().nullable(),
    dividends: z.number().nullable(),
    emission_tao: z.number().nullable(),
    stake_tao: z.number().nullable(),
    registered_at_block: z.int().nullable(),
    is_immunity_period: z.boolean().nullable(),
    axon: z.string().nullable(),
    block_number: z.int().nullable(),
    captured_at: z.int().nullable(),
    take: z.number().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_identity` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetIdentityRowSchema = z
  .object({
    netuid: z.int().nullable(),
    block_number: z.int().nullable(),
    captured_at: z.int().nullable(),
    subnet_name: z.string().nullable(),
    symbol: z.string().nullable(),
    description: z.string().nullable(),
    github_repo: z.string().nullable(),
    subnet_url: z.string().nullable(),
    discord: z.string().nullable(),
    logo_url: z.string().nullable(),
    identity_hash: z.string().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnet_ownership` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetOwnershipRowSchema = z
  .object({
    netuid: z.int().nullable(),
    owner_hotkey: z.string().nullable(),
    owner_coldkey: z.string().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.subnets` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SubnetsRowSchema = z
  .object({
    netuid: z.int().nullable(),
    slug: z.string().nullable(),
    name: z.string().nullable(),
    source: z.string().nullable(),
    overlay: z.string().nullable(),
    source_commit: z.string().nullable(),
    updated_at: z.iso.datetime().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.surfaces` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const SurfacesRowSchema = z
  .object({
    id: z.base64().nullable(),
    subnet_netuid: z.int().nullable(),
    provider_id: z.string().nullable(),
    surface_key: z.string().nullable(),
    kind: z.string().nullable(),
    url: z.string().nullable(),
    authority: z.string().nullable(),
    review_state: z.string().nullable(),
    probe_eligible: z.boolean().nullable(),
    public_safe: z.boolean().nullable(),
    overlay: z.string().nullable(),
    source_commit: z.string().nullable(),
    updated_at: z.iso.datetime().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.providers` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const ProvidersRowSchema = z
  .object({
    id: z.string().nullable(),
    overlay: z.string().nullable(),
    source_commit: z.string().nullable(),
    updated_at: z.iso.datetime().nullable(),
    observed_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/**
 * `chain.validator_nominator_counts` as the catalog declares it.
 *
 * OPEN (`.catchall`) on purpose: a read selects a projection, and often
 * an aggregate alias that is not a column at all. Closed would delete it.
 * PARTIAL on purpose: a projection carries a subset of the columns.
 * What stays pinned is the TYPE of any declared column that IS present.
 */
export const ValidatorNominatorCountsRowSchema = z
  .object({
    hotkey: z.string().nullable(),
    nominator_count: z.int().nullable(),
    captured_at: z.int().nullable(),
  })
  .partial()
  .catchall(z.unknown());

/** Every table's row schema, by table name. */
export const LAKEHOUSE_ROW_SCHEMAS = {
  blocks: BlocksRowSchema,
  extrinsics: ExtrinsicsRowSchema,
  chain_events: ChainEventsRowSchema,
  account_events: AccountEventsRowSchema,
  account_identity: AccountIdentityRowSchema,
  account_identity_history: AccountIdentityHistoryRowSchema,
  nominator_positions: NominatorPositionsRowSchema,
  rpc_proxy_events: RpcProxyEventsRowSchema,
  self_health_daily: SelfHealthDailyRowSchema,
  subnet_hyperparams: SubnetHyperparamsRowSchema,
  subnet_hyperparams_history: SubnetHyperparamsHistoryRowSchema,
  subnet_identity_history: SubnetIdentityHistoryRowSchema,
  subnet_ownership_history: SubnetOwnershipHistoryRowSchema,
  neuron_daily: NeuronDailyRowSchema,
  account_position_daily: AccountPositionDailyRowSchema,
  subnet_snapshots: SubnetSnapshotsRowSchema,
  account_balances: AccountBalancesRowSchema,
  neurons: NeuronsRowSchema,
  subnet_identity: SubnetIdentityRowSchema,
  subnet_ownership: SubnetOwnershipRowSchema,
  subnets: SubnetsRowSchema,
  surfaces: SurfacesRowSchema,
  providers: ProvidersRowSchema,
  validator_nominator_counts: ValidatorNominatorCountsRowSchema,
} as const;
