-- Make the history tables' surrogate id mean the same thing in both stores
-- (#9954).
--
-- 0003 declared `id ... GENERATED ALWAYS AS IDENTITY` on the four
-- AUTOINCREMENT history tables, reasoning that the id was "a tiebreaker that
-- can never tie" because the natural key is unique. That was wrong twice over,
-- and both ways are load bearing:
--
--   THE WRITE PATH PICKS THE LATEST REVISION BY MAX(id). workers/data-api.ts
--   joins `(SELECT netuid, MAX(id) FROM subnet_hyperparams_history GROUP BY
--   netuid)` to decide whether a hyperparameter set has changed. D1 numbered
--   by INSERTION order and the backfill inserted in KEYSET order, so the two
--   stores disagree about which row is newest. Measured: id=1 is
--   5HdThE9Wvusf... in D1 and 5C5LVkCfXk4L... in Neon.
--
--   observed_at IS NOT UNIQUE, it has merely not collided. Every row in one
--   sync shares a single `now`, so two revisions written in the same
--   millisecond share observed_at and ONLY the id orders them.
--   tests/data-api-hyperparams-identity-d1.test.ts constructs exactly that
--   case. The production sample is 137/137 and 531/531 distinct because ticks
--   are far apart, not because a collision is impossible.
--
-- So the id is part of the contract, and D1 is its authority until D1 is gone.
--
-- WHY TRUNCATE IS SAFE HERE, AND WHY IT IS NECESSARY. Necessary because the
-- rows already in Neon carry the WRONG ids: renumbering them in place would
-- collide, since the id a row needs is frequently one another row currently
-- holds. Safe because no route reads these tables from Neon -- they are absent
-- from NEON_READ_LANES, every read still goes to D1 -- and every row is
-- reconstructible from D1 by the backfill, which refills them within one tick.
-- 768 rows across the four.
--
-- THE SEQUENCE IS PARKED ABOVE D1'S RANGE rather than left at 1. Every insert
-- into these tables now supplies an explicit id copied from D1, so the
-- sequence should never be drawn from at all -- but if one ever were, starting
-- at 1 would hand back an id some copied row already holds. Parking it at a
-- billion makes an accidental generated id obvious and harmless instead of a
-- primary-key collision.

ALTER TABLE account_identity_history ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE subnet_hyperparams_history ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE emission_gate_param_history ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE subnet_emission_enabled_history ALTER COLUMN id SET GENERATED BY DEFAULT;

TRUNCATE account_identity_history;
TRUNCATE subnet_hyperparams_history;
TRUNCATE emission_gate_param_history;
TRUNCATE subnet_emission_enabled_history;

SELECT setval(pg_get_serial_sequence('account_identity_history', 'id'), 1000000000, false);
SELECT setval(pg_get_serial_sequence('subnet_hyperparams_history', 'id'), 1000000000, false);
SELECT setval(pg_get_serial_sequence('emission_gate_param_history', 'id'), 1000000000, false);
SELECT setval(pg_get_serial_sequence('subnet_emission_enabled_history', 'id'), 1000000000, false);
