import { createFileRoute } from "@tanstack/react-router";
import { llms } from "fumadocs-core/source/llms";
import { docsSource } from "@/lib/docs-source";
import { llmsIndexBody, llmsIndexHeaders } from "@/lib/metagraphed/llms-index";

const docsLlms = llms(docsSource);

// Distinct from the existing repo-wide public/llms.txt (registry/API-surface
// data, generated by scripts/build-artifacts.ts) -- this is the prose/guide
// content under /docs/*, sourced live from docsSource so it grows
// automatically as more pages are migrated, with no separate build step.
export const Route = createFileRoute("/docs/llms.txt")({
  server: {
    handlers: {
      GET: ({ request }) => {
        const { origin } = new URL(request.url);
        return new Response(
          llmsIndexBody({
            index: docsLlms.index(),
            section: "docs",
            origin,
            title: "Metagraphed documentation",
            example: "mcp",
          }),
          { headers: llmsIndexHeaders() },
        );
      },
    },
  },
});
