import { createFileRoute } from "@tanstack/react-router";
import { llmsIndexBody, llmsIndexHeaders } from "@/lib/metagraphed/llms-index";

// Distinct from the existing repo-wide public/llms.txt (registry/API-surface
// data, generated by scripts/build-artifacts.ts) -- this is the prose/guide
// content under /docs/*, sourced live from docsSource so it grows
// automatically as more pages are migrated, with no separate build step.
export const Route = createFileRoute("/docs/llms.txt")({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const [{ llms }, { docsSource }] = await Promise.all([
          import("fumadocs-core/source/llms"),
          import("@/lib/docs-source"),
        ]);
        const { origin } = new URL(request.url);
        return new Response(
          llmsIndexBody({
            index: llms(docsSource).index(),
            section: "docs",
            origin,
            title: "Metagraphed documentation",
            example: "mcp",
          }),
          { headers: llmsIndexHeaders() },
        );
      },
    },
  },
});
