--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_balances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_balances (
    ss58 text NOT NULL,
    free_tao double precision NOT NULL,
    reserved_tao double precision NOT NULL,
    captured_at bigint NOT NULL
);

--
-- Name: account_balances_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_balances_passes (
    captured_at bigint NOT NULL,
    expected_rows integer NOT NULL,
    received_rows integer DEFAULT 0 NOT NULL,
    completed_at bigint,
    scanned integer,
    outcome text
);

--
-- Name: account_identity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_identity (
    account text NOT NULL,
    name text,
    url text,
    github text,
    image text,
    discord text,
    description text,
    additional text,
    captured_at bigint NOT NULL
);

--
-- Name: account_identity_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_identity_history (
    id bigint NOT NULL,
    account text NOT NULL,
    observed_at bigint NOT NULL,
    name text,
    url text,
    github text,
    image text,
    discord text,
    description text,
    additional text,
    identity_hash text NOT NULL
);

--
-- Name: account_identity_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_identity_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_identity_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: account_position_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_position_daily (
    account text NOT NULL,
    netuid integer NOT NULL,
    snapshot_date text NOT NULL,
    uid integer,
    coldkey text,
    active boolean,
    validator_permit boolean,
    rank double precision,
    trust double precision,
    incentive double precision,
    dividends double precision,
    stake_tao double precision,
    emission_tao double precision,
    captured_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT account_position_daily_captured_at_is_millis CHECK ((captured_at >= '1000000000000'::bigint))
);

--
-- Name: api_key_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_key_blocks (
    id integer NOT NULL,
    account_id integer NOT NULL,
    reason_code text NOT NULL,
    note text,
    blocked_at bigint NOT NULL,
    blocked_by text,
    unblocked_at bigint,
    unblocked_note text
);

--
-- Name: api_key_blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_key_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_key_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: api_key_usage_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_key_usage_daily (
    account_id integer NOT NULL,
    day text NOT NULL,
    route text NOT NULL,
    request_count integer DEFAULT 0 NOT NULL,
    rejected_count integer DEFAULT 0 NOT NULL
);

--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id integer NOT NULL,
    prefix text,
    secret_hash text,
    owner_contact text NOT NULL,
    tier text DEFAULT 'keyed'::text NOT NULL,
    created_at bigint NOT NULL,
    revoked_at bigint,
    last_used_at bigint,
    account_id integer,
    unkey_key_id text
);

--
-- Name: api_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: api_quota_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_quota_daily (
    account_id integer NOT NULL,
    day text NOT NULL,
    units_spent bigint DEFAULT 0 NOT NULL,
    updated_at bigint NOT NULL
);

--
-- Name: api_usage_rollup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_usage_rollup (
    day text NOT NULL,
    route_family text NOT NULL,
    cost_shape text NOT NULL,
    request_count bigint DEFAULT 0 NOT NULL,
    keyed_count bigint DEFAULT 0 NOT NULL
);

--
-- Name: attribution_candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attribution_candidates (
    netuid integer NOT NULL,
    ss58 text NOT NULL,
    source_url text NOT NULL,
    first_seen bigint NOT NULL,
    last_seen bigint NOT NULL,
    CONSTRAINT attribution_candidates_first_seen_is_millis CHECK ((first_seen >= '1000000000000'::bigint)),
    CONSTRAINT attribution_candidates_last_seen_is_millis CHECK ((last_seen >= '1000000000000'::bigint))
);

--
-- Name: attribution_sweeps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attribution_sweeps (
    netuid integer NOT NULL,
    swept_at bigint NOT NULL,
    sources_checked integer NOT NULL,
    sources_read integer NOT NULL,
    candidates integer NOT NULL,
    verdict text NOT NULL,
    CONSTRAINT attribution_sweeps_counts_are_sane CHECK (((sources_checked >= 0) AND (sources_read >= 0) AND (sources_read <= sources_checked) AND (candidates >= 0))),
    CONSTRAINT attribution_sweeps_swept_at_is_millis CHECK ((swept_at >= '1000000000000'::bigint)),
    CONSTRAINT attribution_sweeps_verdict_is_known CHECK ((verdict = ANY (ARRAY['none-published'::text, 'candidates-found'::text, 'unreachable'::text, 'no-sources'::text])))
);

--
-- Name: blocks_head; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blocks_head (
    block_number integer NOT NULL,
    block_hash text NOT NULL,
    parent_hash text,
    extrinsic_count integer,
    event_count integer,
    author text,
    observed_at bigint NOT NULL
);

--
-- Name: chain_alert_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_alert_deliveries (
    id integer NOT NULL,
    trigger_id integer NOT NULL,
    delivered_at bigint NOT NULL,
    success boolean NOT NULL,
    status_code integer,
    retry_count integer DEFAULT 0 NOT NULL,
    response_snippet text
);

--
-- Name: chain_alert_deliveries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chain_alert_deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chain_alert_deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: chain_alert_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_alert_triggers (
    id integer NOT NULL,
    owner_token text NOT NULL,
    name text,
    table_filter text,
    netuid integer,
    event_kind text,
    account text,
    min_amount_tao double precision,
    channel text NOT NULL,
    destination text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    last_matched_at bigint,
    match_count integer DEFAULT 0 NOT NULL,
    condition text,
    owner_ss58 text,
    CONSTRAINT chain_alert_triggers_channel_check CHECK ((channel = ANY (ARRAY['webhook'::text, 'email'::text, 'telegram'::text, 'discord'::text, 'webpush'::text])))
);

--
-- Name: chain_alert_triggers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chain_alert_triggers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chain_alert_triggers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: chain_concentration_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_concentration_daily (
    day text NOT NULL,
    neuron_count integer NOT NULL,
    card text NOT NULL,
    source_captured_at bigint,
    computed_at bigint NOT NULL,
    builder_version integer NOT NULL
);

--
-- Name: chain_detail_account_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_detail_account_events (
    block_number integer NOT NULL,
    event_index integer NOT NULL,
    extrinsic_index integer,
    event_kind text NOT NULL,
    hotkey text,
    coldkey text,
    netuid integer,
    uid integer,
    amount_tao text,
    alpha_amount text,
    observed_at bigint NOT NULL
);

--
-- Name: chain_detail_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_detail_blocks (
    block_number integer NOT NULL,
    block_hash text NOT NULL,
    spec_version integer,
    extrinsic_count integer NOT NULL,
    chain_event_count integer NOT NULL,
    account_event_count integer NOT NULL,
    observed_at bigint NOT NULL,
    synced_at bigint NOT NULL
);

--
-- Name: chain_detail_chain_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_detail_chain_events (
    block_number integer NOT NULL,
    event_index integer NOT NULL,
    pallet text NOT NULL,
    method text NOT NULL,
    args text,
    phase text NOT NULL,
    extrinsic_index integer,
    observed_at bigint NOT NULL
);

--
-- Name: chain_detail_extrinsics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chain_detail_extrinsics (
    block_number integer NOT NULL,
    extrinsic_index integer NOT NULL,
    extrinsic_hash text,
    signer text,
    call_module text,
    call_function text,
    success boolean,
    fee_tao text,
    tip_tao text,
    call_args text,
    observed_at bigint NOT NULL
);

--
-- Name: emission_flow_watch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emission_flow_watch (
    id integer NOT NULL,
    item text NOT NULL,
    netuid integer,
    is_set boolean NOT NULL,
    ema_block integer,
    block_number integer,
    observed_at bigint NOT NULL,
    predates_capture boolean DEFAULT false NOT NULL,
    CONSTRAINT emission_flow_watch_check CHECK ((((item = 'subnet_ema_tao_flow'::text) AND (netuid IS NOT NULL) AND (ema_block IS NOT NULL)) OR ((item <> 'subnet_ema_tao_flow'::text) AND (netuid IS NULL) AND (ema_block IS NULL)))),
    CONSTRAINT emission_flow_watch_item_check CHECK ((item = ANY (ARRAY['net_tao_flow_enabled'::text, 'flow_norm_exponent'::text, 'tao_flow_cutoff'::text, 'flow_ema_smoothing_factor'::text, 'subnet_ema_tao_flow'::text])))
);

--
-- Name: emission_flow_watch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emission_flow_watch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emission_flow_watch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: emission_gate_param_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emission_gate_param_history (
    id bigint NOT NULL,
    param text NOT NULL,
    value double precision,
    previous_value double precision,
    source text NOT NULL,
    block_number bigint,
    observed_at bigint NOT NULL,
    predates_capture boolean DEFAULT false NOT NULL,
    CONSTRAINT emission_gate_param_history_source_check CHECK ((source = ANY (ARRAY['governance'::text, 'runtime_recomputed'::text])))
);

--
-- Name: emission_gate_param_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emission_gate_param_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emission_gate_param_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: github_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.github_accounts (
    id integer NOT NULL,
    github_user_id bigint NOT NULL,
    github_login text NOT NULL,
    tier text DEFAULT 'free'::text NOT NULL,
    created_at bigint NOT NULL,
    last_login_at bigint
);

--
-- Name: github_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.github_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.github_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: hotkey_alpha; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotkey_alpha (
    hotkey text NOT NULL,
    netuid integer NOT NULL,
    total_alpha double precision NOT NULL,
    captured_at bigint NOT NULL
);

--
-- Name: hotkey_alpha_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotkey_alpha_passes (
    captured_at bigint NOT NULL,
    expected_rows integer NOT NULL,
    received_rows integer DEFAULT 0 NOT NULL,
    completed_at bigint
);

--
-- Name: lane_health; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lane_health (
    lane text NOT NULL,
    verdict text NOT NULL,
    age_ms bigint,
    detail text,
    checked_at bigint NOT NULL
);

--
-- Name: neuron_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.neuron_daily (
    netuid integer NOT NULL,
    uid integer NOT NULL,
    hotkey text,
    coldkey text,
    active boolean,
    validator_permit boolean,
    rank double precision,
    trust double precision,
    validator_trust double precision,
    consensus double precision,
    incentive double precision,
    dividends double precision,
    emission_tao double precision,
    stake_tao double precision,
    registered_at_block bigint,
    is_immunity_period boolean,
    axon text,
    block_number bigint,
    captured_at bigint NOT NULL,
    take double precision,
    snapshot_date text NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT neuron_daily_captured_at_is_millis CHECK ((captured_at >= '1000000000000'::bigint))
);

--
-- Name: neurons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.neurons (
    netuid integer NOT NULL,
    uid integer NOT NULL,
    hotkey text,
    coldkey text,
    active boolean,
    validator_permit boolean,
    rank double precision,
    trust double precision,
    validator_trust double precision,
    consensus double precision,
    incentive double precision,
    dividends double precision,
    emission_tao double precision,
    stake_tao double precision,
    registered_at_block bigint,
    is_immunity_period boolean,
    axon text,
    block_number bigint,
    captured_at bigint NOT NULL,
    take double precision
);

--
-- Name: neurons_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.neurons_passes (
    captured_at bigint NOT NULL,
    expected_rows integer NOT NULL,
    received_rows integer DEFAULT 0 NOT NULL,
    completed_at bigint
);

--
-- Name: nominator_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nominator_positions (
    coldkey text NOT NULL,
    hotkey text NOT NULL,
    netuid integer NOT NULL,
    share_fraction double precision,
    captured_at bigint NOT NULL
);

--
-- Name: nominator_positions_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nominator_positions_passes (
    captured_at bigint NOT NULL,
    expected_rows integer NOT NULL,
    received_rows integer DEFAULT 0 NOT NULL,
    completed_at bigint
);

--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id text NOT NULL,
    "overlay" text NOT NULL,
    source_commit text NOT NULL,
    updated_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint NOT NULL
);

--
-- Name: raw_capture_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_capture_state (
    network text NOT NULL,
    last_contiguous_block integer NOT NULL,
    updated_at bigint NOT NULL,
    stopped_at bigint,
    last_error text
);

--
-- Name: revenue_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revenue_observations (
    surface_id text NOT NULL,
    netuid integer NOT NULL,
    period text NOT NULL,
    grain text NOT NULL,
    amount double precision NOT NULL,
    currency text NOT NULL,
    provenance text NOT NULL,
    response_hash text NOT NULL,
    observed_at bigint NOT NULL,
    CONSTRAINT revenue_observations_observed_at_is_millis CHECK ((observed_at >= '1000000000000'::bigint)),
    CONSTRAINT revenue_observations_provenance_is_readable CHECK ((provenance = ANY (ARRAY['probe-derived'::text, 'chain-verified'::text])))
);

--
-- Name: revenue_probe_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revenue_probe_failures (
    surface_id text NOT NULL,
    netuid integer NOT NULL,
    reason text NOT NULL,
    observed_at bigint NOT NULL,
    CONSTRAINT revenue_probe_failures_observed_at_is_millis CHECK ((observed_at >= '1000000000000'::bigint))
);

--
-- Name: rpc_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rpc_accounts (
    id integer NOT NULL,
    ss58 text NOT NULL,
    tier text DEFAULT 'free'::text NOT NULL,
    created_at bigint NOT NULL,
    last_login_at bigint
);

--
-- Name: rpc_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rpc_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rpc_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: self_health_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.self_health_checks (
    component text NOT NULL,
    checked_at_ms bigint NOT NULL,
    ok boolean NOT NULL,
    http_status integer,
    latency_ms integer
);

--
-- Name: self_health_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.self_health_daily (
    day date NOT NULL,
    component text NOT NULL,
    checks integer NOT NULL,
    ok_count integer NOT NULL
);

--
-- Name: subnet_burn_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_burn_history (
    netuid integer NOT NULL,
    observed_at bigint NOT NULL,
    burn_tao double precision NOT NULL
);

--
-- Name: subnet_deregistration_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_deregistration_daily (
    netuid integer NOT NULL,
    snapshot_date text NOT NULL,
    moving_price double precision,
    registered_at_block bigint,
    subnet_mechanism integer,
    network_immunity_period bigint,
    pinned_block bigint,
    captured_at bigint NOT NULL,
    CONSTRAINT subnet_deregistration_daily_captured_at_is_millis CHECK ((captured_at >= '1000000000000'::bigint))
);

--
-- Name: subnet_emission_enabled_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_emission_enabled_history (
    id bigint NOT NULL,
    netuid integer NOT NULL,
    enabled boolean NOT NULL,
    previous_enabled boolean,
    block_number bigint,
    observed_at bigint NOT NULL,
    predates_capture boolean DEFAULT false NOT NULL
);

--
-- Name: subnet_emission_enabled_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subnet_emission_enabled_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subnet_emission_enabled_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: subnet_hyperparams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_hyperparams (
    netuid integer NOT NULL,
    kappa_ratio double precision,
    immunity_period integer,
    min_allowed_weights integer,
    max_weight_limit_ratio double precision,
    tempo integer,
    weights_version bigint,
    weights_rate_limit double precision,
    activity_cutoff integer,
    activity_cutoff_factor integer,
    registration_allowed boolean,
    target_regs_per_interval integer,
    min_burn_tao double precision,
    max_burn_tao double precision,
    burn_half_life integer,
    burn_increase_mult double precision,
    bonds_moving_avg_raw bigint,
    max_regs_per_block integer,
    serving_rate_limit integer,
    max_validators integer,
    commit_reveal_period integer,
    commit_reveal_enabled boolean,
    alpha_high_ratio double precision,
    alpha_low_ratio double precision,
    liquid_alpha_enabled boolean,
    alpha_sigmoid_steepness double precision,
    yuma_version integer,
    subnet_is_active boolean,
    transfers_enabled boolean,
    bonds_reset_enabled boolean,
    user_liquidity_enabled boolean,
    owner_cut_enabled boolean,
    owner_cut_auto_lock_enabled boolean,
    min_childkey_take_ratio double precision,
    block_number integer,
    captured_at bigint NOT NULL
);

--
-- Name: subnet_hyperparams_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_hyperparams_history (
    id bigint NOT NULL,
    netuid integer NOT NULL,
    block_number bigint,
    observed_at bigint NOT NULL,
    kappa_ratio double precision,
    immunity_period integer,
    min_allowed_weights integer,
    max_weight_limit_ratio double precision,
    tempo integer,
    weights_version bigint,
    weights_rate_limit double precision,
    activity_cutoff integer,
    activity_cutoff_factor integer,
    registration_allowed boolean,
    target_regs_per_interval integer,
    min_burn_tao double precision,
    max_burn_tao double precision,
    burn_half_life integer,
    burn_increase_mult double precision,
    bonds_moving_avg_raw bigint,
    max_regs_per_block integer,
    serving_rate_limit integer,
    max_validators integer,
    commit_reveal_period integer,
    commit_reveal_enabled boolean,
    alpha_high_ratio double precision,
    alpha_low_ratio double precision,
    liquid_alpha_enabled boolean,
    alpha_sigmoid_steepness double precision,
    yuma_version integer,
    subnet_is_active boolean,
    transfers_enabled boolean,
    bonds_reset_enabled boolean,
    user_liquidity_enabled boolean,
    owner_cut_enabled boolean,
    owner_cut_auto_lock_enabled boolean,
    min_childkey_take_ratio double precision,
    hyperparams_hash text NOT NULL
);

--
-- Name: subnet_hyperparams_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subnet_hyperparams_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subnet_hyperparams_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: subnet_lifecycle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_lifecycle (
    id bigint NOT NULL,
    netuid integer NOT NULL,
    event text NOT NULL,
    block_number bigint,
    observed_at bigint NOT NULL,
    predates_capture boolean DEFAULT false NOT NULL,
    CONSTRAINT subnet_lifecycle_event_known CHECK ((event = ANY (ARRAY['registered'::text, 'deregistered'::text]))),
    CONSTRAINT subnet_lifecycle_observed_at_is_millis CHECK ((observed_at >= '1000000000000'::bigint))
);

--
-- Name: subnet_lifecycle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.subnet_lifecycle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: subnet_lifecycle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.subnet_lifecycle_id_seq OWNED BY public.subnet_lifecycle.id;

--
-- Name: subnet_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnet_snapshots (
    netuid integer NOT NULL,
    snapshot_date text NOT NULL,
    completeness_score integer,
    surface_count integer,
    endpoint_count integer,
    monitored_count integer,
    candidate_count integer,
    captured_at bigint,
    validator_count integer,
    miner_count integer,
    total_stake_tao double precision,
    alpha_price_tao double precision,
    emission_share double precision,
    tao_in_pool_tao double precision,
    alpha_in_pool double precision,
    alpha_out_pool double precision,
    subnet_volume_tao double precision,
    tao_in_emission_tao double precision,
    excess_tao double precision,
    alpha_in_emission double precision,
    alpha_out_emission double precision,
    miner_burned_fraction double precision,
    emission_enabled boolean,
    subtoken_enabled boolean,
    first_emission_block integer,
    pipeline_block integer,
    pipeline_block_hash text
);

--
-- Name: subnets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subnets (
    netuid integer NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    source text DEFAULT 'community'::text NOT NULL,
    "overlay" text NOT NULL,
    source_commit text NOT NULL,
    updated_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint NOT NULL
);

--
-- Name: surface_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surface_checks (
    surface_id text NOT NULL,
    surface_key text,
    netuid integer,
    kind text,
    status text,
    classification text,
    latency_ms integer,
    status_code integer,
    ok boolean,
    checked_at bigint NOT NULL
);

--
-- Name: surface_failure_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surface_failure_daily (
    day text NOT NULL,
    netuid integer,
    kind text NOT NULL,
    classification text NOT NULL,
    checks integer NOT NULL,
    updated_at bigint NOT NULL
);

--
-- Name: surface_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surface_history (
    id integer NOT NULL,
    surface_id text,
    subnet_netuid integer NOT NULL,
    action text NOT NULL,
    "overlay" text NOT NULL,
    source_commit text NOT NULL,
    recorded_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint NOT NULL
);

--
-- Name: surface_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.surface_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.surface_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: surface_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surface_status (
    surface_id text NOT NULL,
    surface_key text,
    netuid integer,
    kind text,
    url text,
    provider text,
    status text,
    classification text,
    latency_ms integer,
    status_code integer,
    last_checked bigint,
    last_ok bigint,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    updated_at bigint
);

--
-- Name: surface_uptime_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surface_uptime_daily (
    surface_id text NOT NULL,
    surface_key text,
    netuid integer,
    day text NOT NULL,
    samples integer NOT NULL,
    ok_count integer NOT NULL,
    uptime_ratio double precision,
    avg_latency_ms integer,
    status text,
    latency_samples integer,
    p50_latency_ms integer,
    p95_latency_ms integer,
    p99_latency_ms integer,
    updated_at bigint
);

--
-- Name: surfaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surfaces (
    id text NOT NULL,
    subnet_netuid integer NOT NULL,
    provider_id text,
    surface_key text NOT NULL,
    kind text NOT NULL,
    url text NOT NULL,
    authority text DEFAULT 'community'::text NOT NULL,
    review_state text DEFAULT 'community-submitted'::text NOT NULL,
    probe_eligible boolean DEFAULT false NOT NULL,
    public_safe boolean DEFAULT true NOT NULL,
    "overlay" text NOT NULL,
    source_commit text NOT NULL,
    updated_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint NOT NULL
);

--
-- Name: tao_usd_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tao_usd_index (
    block_number bigint NOT NULL,
    observed_at bigint NOT NULL,
    usd_per_tao double precision,
    price_basis text NOT NULL,
    eth_usd double precision,
    pool_count integer NOT NULL,
    pools text DEFAULT '[]'::text NOT NULL,
    CONSTRAINT tao_usd_index_check CHECK ((((price_basis = 'insufficient_pools'::text) AND (usd_per_tao IS NULL)) OR ((price_basis <> 'insufficient_pools'::text) AND (usd_per_tao IS NOT NULL)))),
    CONSTRAINT tao_usd_index_pool_count_check CHECK ((pool_count >= 0)),
    CONSTRAINT tao_usd_index_price_basis_check CHECK ((price_basis = ANY (ARRAY['wrapped_onchain_median'::text, 'insufficient_pools'::text])))
);

--
-- Name: validator_nominator_counts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.validator_nominator_counts (
    hotkey text NOT NULL,
    nominator_count integer NOT NULL,
    captured_at bigint NOT NULL
);

--
-- Name: validator_nominator_counts_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.validator_nominator_counts_passes (
    captured_at bigint NOT NULL,
    expected_rows integer NOT NULL,
    received_rows integer DEFAULT 0 NOT NULL,
    completed_at bigint
);

--
-- Name: watch_push_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.watch_push_subscriptions (
    id integer NOT NULL,
    address text NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_agent text,
    created_at bigint NOT NULL,
    last_used_at bigint
);

--
-- Name: watch_push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.watch_push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: subnet_lifecycle id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_lifecycle ALTER COLUMN id SET DEFAULT nextval('public.subnet_lifecycle_id_seq'::regclass);

--
-- Name: account_balances_passes account_balances_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_balances_passes
    ADD CONSTRAINT account_balances_passes_pkey PRIMARY KEY (captured_at);

--
-- Name: account_balances account_balances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_balances
    ADD CONSTRAINT account_balances_pkey PRIMARY KEY (ss58);

--
-- Name: account_identity_history account_identity_history_account_observed_at_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_identity_history
    ADD CONSTRAINT account_identity_history_account_observed_at_key UNIQUE (account, observed_at);

--
-- Name: account_identity_history account_identity_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_identity_history
    ADD CONSTRAINT account_identity_history_pkey PRIMARY KEY (id);

--
-- Name: account_identity account_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_identity
    ADD CONSTRAINT account_identity_pkey PRIMARY KEY (account);

--
-- Name: account_position_daily account_position_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_position_daily
    ADD CONSTRAINT account_position_daily_pkey PRIMARY KEY (account, netuid, snapshot_date);

--
-- Name: api_key_blocks api_key_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_blocks
    ADD CONSTRAINT api_key_blocks_pkey PRIMARY KEY (id);

--
-- Name: api_key_usage_daily api_key_usage_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_usage_daily
    ADD CONSTRAINT api_key_usage_daily_pkey PRIMARY KEY (account_id, day, route);

--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

--
-- Name: api_keys api_keys_prefix_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_prefix_key UNIQUE (prefix);

--
-- Name: api_quota_daily api_quota_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_quota_daily
    ADD CONSTRAINT api_quota_daily_pkey PRIMARY KEY (account_id, day);

--
-- Name: api_usage_rollup api_usage_rollup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_usage_rollup
    ADD CONSTRAINT api_usage_rollup_pkey PRIMARY KEY (day, route_family, cost_shape);

--
-- Name: attribution_candidates attribution_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attribution_candidates
    ADD CONSTRAINT attribution_candidates_pkey PRIMARY KEY (netuid, ss58, source_url);

--
-- Name: attribution_sweeps attribution_sweeps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attribution_sweeps
    ADD CONSTRAINT attribution_sweeps_pkey PRIMARY KEY (netuid);

--
-- Name: blocks_head blocks_head_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks_head
    ADD CONSTRAINT blocks_head_pkey PRIMARY KEY (block_number);

--
-- Name: chain_alert_deliveries chain_alert_deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_alert_deliveries
    ADD CONSTRAINT chain_alert_deliveries_pkey PRIMARY KEY (id);

--
-- Name: chain_alert_triggers chain_alert_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_alert_triggers
    ADD CONSTRAINT chain_alert_triggers_pkey PRIMARY KEY (id);

--
-- Name: chain_concentration_daily chain_concentration_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_concentration_daily
    ADD CONSTRAINT chain_concentration_daily_pkey PRIMARY KEY (day);

--
-- Name: chain_detail_account_events chain_detail_account_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_detail_account_events
    ADD CONSTRAINT chain_detail_account_events_pkey PRIMARY KEY (block_number, event_index);

--
-- Name: chain_detail_blocks chain_detail_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_detail_blocks
    ADD CONSTRAINT chain_detail_blocks_pkey PRIMARY KEY (block_number);

--
-- Name: chain_detail_chain_events chain_detail_chain_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_detail_chain_events
    ADD CONSTRAINT chain_detail_chain_events_pkey PRIMARY KEY (block_number, event_index);

--
-- Name: chain_detail_extrinsics chain_detail_extrinsics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_detail_extrinsics
    ADD CONSTRAINT chain_detail_extrinsics_pkey PRIMARY KEY (block_number, extrinsic_index);

--
-- Name: emission_flow_watch emission_flow_watch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emission_flow_watch
    ADD CONSTRAINT emission_flow_watch_pkey PRIMARY KEY (id);

--
-- Name: emission_gate_param_history emission_gate_param_history_param_observed_at_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emission_gate_param_history
    ADD CONSTRAINT emission_gate_param_history_param_observed_at_key UNIQUE (param, observed_at);

--
-- Name: emission_gate_param_history emission_gate_param_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emission_gate_param_history
    ADD CONSTRAINT emission_gate_param_history_pkey PRIMARY KEY (id);

--
-- Name: github_accounts github_accounts_github_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.github_accounts
    ADD CONSTRAINT github_accounts_github_user_id_key UNIQUE (github_user_id);

--
-- Name: github_accounts github_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.github_accounts
    ADD CONSTRAINT github_accounts_pkey PRIMARY KEY (id);

--
-- Name: hotkey_alpha_passes hotkey_alpha_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotkey_alpha_passes
    ADD CONSTRAINT hotkey_alpha_passes_pkey PRIMARY KEY (captured_at);

--
-- Name: hotkey_alpha hotkey_alpha_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotkey_alpha
    ADD CONSTRAINT hotkey_alpha_pkey PRIMARY KEY (hotkey, netuid);

--
-- Name: neuron_daily neuron_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.neuron_daily
    ADD CONSTRAINT neuron_daily_pkey PRIMARY KEY (netuid, uid, snapshot_date);

--
-- Name: neurons_passes neurons_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.neurons_passes
    ADD CONSTRAINT neurons_passes_pkey PRIMARY KEY (captured_at);

--
-- Name: neurons neurons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.neurons
    ADD CONSTRAINT neurons_pkey PRIMARY KEY (netuid, uid);

--
-- Name: nominator_positions_passes nominator_positions_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominator_positions_passes
    ADD CONSTRAINT nominator_positions_passes_pkey PRIMARY KEY (captured_at);

--
-- Name: nominator_positions nominator_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominator_positions
    ADD CONSTRAINT nominator_positions_pkey PRIMARY KEY (coldkey, hotkey, netuid);

--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);

--
-- Name: raw_capture_state raw_capture_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_capture_state
    ADD CONSTRAINT raw_capture_state_pkey PRIMARY KEY (network);

--
-- Name: revenue_observations revenue_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revenue_observations
    ADD CONSTRAINT revenue_observations_pkey PRIMARY KEY (surface_id, period);

--
-- Name: revenue_probe_failures revenue_probe_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revenue_probe_failures
    ADD CONSTRAINT revenue_probe_failures_pkey PRIMARY KEY (surface_id, observed_at);

--
-- Name: rpc_accounts rpc_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rpc_accounts
    ADD CONSTRAINT rpc_accounts_pkey PRIMARY KEY (id);

--
-- Name: rpc_accounts rpc_accounts_ss58_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rpc_accounts
    ADD CONSTRAINT rpc_accounts_ss58_key UNIQUE (ss58);

--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);

--
-- Name: self_health_checks self_health_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_health_checks
    ADD CONSTRAINT self_health_checks_pkey PRIMARY KEY (component, checked_at_ms);

--
-- Name: self_health_daily self_health_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_health_daily
    ADD CONSTRAINT self_health_daily_pkey PRIMARY KEY (day, component);

--
-- Name: subnet_burn_history subnet_burn_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_burn_history
    ADD CONSTRAINT subnet_burn_history_pkey PRIMARY KEY (netuid, observed_at);

--
-- Name: subnet_deregistration_daily subnet_deregistration_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_deregistration_daily
    ADD CONSTRAINT subnet_deregistration_daily_pkey PRIMARY KEY (netuid, snapshot_date);

--
-- Name: subnet_emission_enabled_history subnet_emission_enabled_history_netuid_observed_at_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_emission_enabled_history
    ADD CONSTRAINT subnet_emission_enabled_history_netuid_observed_at_key UNIQUE (netuid, observed_at);

--
-- Name: subnet_emission_enabled_history subnet_emission_enabled_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_emission_enabled_history
    ADD CONSTRAINT subnet_emission_enabled_history_pkey PRIMARY KEY (id);

--
-- Name: subnet_hyperparams_history subnet_hyperparams_history_netuid_observed_at_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_hyperparams_history
    ADD CONSTRAINT subnet_hyperparams_history_netuid_observed_at_key UNIQUE (netuid, observed_at);

--
-- Name: subnet_hyperparams_history subnet_hyperparams_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_hyperparams_history
    ADD CONSTRAINT subnet_hyperparams_history_pkey PRIMARY KEY (id);

--
-- Name: subnet_hyperparams subnet_hyperparams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_hyperparams
    ADD CONSTRAINT subnet_hyperparams_pkey PRIMARY KEY (netuid);

--
-- Name: subnet_lifecycle subnet_lifecycle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_lifecycle
    ADD CONSTRAINT subnet_lifecycle_pkey PRIMARY KEY (id);

--
-- Name: subnet_snapshots subnet_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnet_snapshots
    ADD CONSTRAINT subnet_snapshots_pkey PRIMARY KEY (netuid, snapshot_date);

--
-- Name: subnets subnets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnets
    ADD CONSTRAINT subnets_pkey PRIMARY KEY (netuid);

--
-- Name: subnets subnets_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subnets
    ADD CONSTRAINT subnets_slug_key UNIQUE (slug);

--
-- Name: surface_checks surface_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surface_checks
    ADD CONSTRAINT surface_checks_pkey PRIMARY KEY (surface_id, checked_at);

--
-- Name: surface_history surface_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surface_history
    ADD CONSTRAINT surface_history_pkey PRIMARY KEY (id);

--
-- Name: surface_status surface_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surface_status
    ADD CONSTRAINT surface_status_pkey PRIMARY KEY (surface_id);

--
-- Name: surface_uptime_daily surface_uptime_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surface_uptime_daily
    ADD CONSTRAINT surface_uptime_daily_pkey PRIMARY KEY (surface_id, day);

--
-- Name: surfaces surfaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surfaces
    ADD CONSTRAINT surfaces_pkey PRIMARY KEY (id);

--
-- Name: surfaces surfaces_subnet_netuid_kind_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surfaces
    ADD CONSTRAINT surfaces_subnet_netuid_kind_url_key UNIQUE (subnet_netuid, kind, url);

--
-- Name: tao_usd_index tao_usd_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tao_usd_index
    ADD CONSTRAINT tao_usd_index_pkey PRIMARY KEY (block_number, observed_at);

--
-- Name: validator_nominator_counts_passes validator_nominator_counts_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.validator_nominator_counts_passes
    ADD CONSTRAINT validator_nominator_counts_passes_pkey PRIMARY KEY (captured_at);

--
-- Name: validator_nominator_counts validator_nominator_counts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.validator_nominator_counts
    ADD CONSTRAINT validator_nominator_counts_pkey PRIMARY KEY (hotkey);

--
-- Name: watch_push_subscriptions watch_push_subscriptions_endpoint_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_push_subscriptions
    ADD CONSTRAINT watch_push_subscriptions_endpoint_key UNIQUE (endpoint);

--
-- Name: watch_push_subscriptions watch_push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_push_subscriptions
    ADD CONSTRAINT watch_push_subscriptions_pkey PRIMARY KEY (id);

--
-- Name: attribution_candidates_by_netuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attribution_candidates_by_netuid ON public.attribution_candidates USING btree (netuid, last_seen DESC);

--
-- Name: emission_flow_watch_item_observed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emission_flow_watch_item_observed_idx ON public.emission_flow_watch USING btree (item, observed_at DESC);

--
-- Name: emission_gate_param_history_param_observed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emission_gate_param_history_param_observed_idx ON public.emission_gate_param_history USING btree (param, observed_at DESC);

--
-- Name: idx_account_balances_passes_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_balances_passes_completed ON public.account_balances_passes USING btree (completed_at DESC);

--
-- Name: idx_account_identity_history_account_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_identity_history_account_observed ON public.account_identity_history USING btree (account, observed_at DESC, id DESC);

--
-- Name: idx_account_position_daily_account_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_position_daily_account_date ON public.account_position_daily USING btree (account, snapshot_date);

--
-- Name: idx_api_key_blocks_one_active_per_account; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_api_key_blocks_one_active_per_account ON public.api_key_blocks USING btree (account_id) WHERE (unblocked_at IS NULL);

--
-- Name: idx_api_key_usage_daily_account_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_key_usage_daily_account_day ON public.api_key_usage_daily USING btree (account_id, day DESC);

--
-- Name: idx_api_keys_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_account_id ON public.api_keys USING btree (account_id) WHERE (account_id IS NOT NULL);

--
-- Name: idx_api_keys_prefix; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_prefix ON public.api_keys USING btree (prefix);

--
-- Name: idx_api_keys_unkey_key_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_api_keys_unkey_key_id ON public.api_keys USING btree (unkey_key_id) WHERE (unkey_key_id IS NOT NULL);

--
-- Name: idx_api_usage_rollup_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_usage_rollup_day ON public.api_usage_rollup USING btree (day DESC, request_count DESC);

--
-- Name: idx_api_usage_rollup_shape; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_usage_rollup_shape ON public.api_usage_rollup USING btree (cost_shape, day DESC);

--
-- Name: idx_blocks_head_hash_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_blocks_head_hash_lower ON public.blocks_head USING btree (lower(block_hash));

--
-- Name: idx_blocks_head_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_blocks_head_observed ON public.blocks_head USING btree (observed_at DESC);

--
-- Name: idx_cad_trigger_delivered_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cad_trigger_delivered_at ON public.chain_alert_deliveries USING btree (trigger_id, delivered_at DESC);

--
-- Name: idx_cat_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cat_active ON public.chain_alert_triggers USING btree (active) WHERE active;

--
-- Name: idx_cat_owner_ss58_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cat_owner_ss58_active ON public.chain_alert_triggers USING btree (owner_ss58) WHERE ((owner_ss58 IS NOT NULL) AND active);

--
-- Name: idx_chain_concentration_daily_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_concentration_daily_day ON public.chain_concentration_daily USING btree (day DESC);

--
-- Name: idx_chain_detail_account_events_extrinsic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_account_events_extrinsic ON public.chain_detail_account_events USING btree (block_number, extrinsic_index);

--
-- Name: idx_chain_detail_account_events_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_account_events_observed ON public.chain_detail_account_events USING btree (observed_at);

--
-- Name: idx_chain_detail_blocks_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_blocks_hash ON public.chain_detail_blocks USING btree (block_hash);

--
-- Name: idx_chain_detail_chain_events_extrinsic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_chain_events_extrinsic ON public.chain_detail_chain_events USING btree (block_number, extrinsic_index);

--
-- Name: idx_chain_detail_chain_events_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_chain_events_observed ON public.chain_detail_chain_events USING btree (observed_at);

--
-- Name: idx_chain_detail_extrinsics_hash_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_extrinsics_hash_lower ON public.chain_detail_extrinsics USING btree (lower(extrinsic_hash));

--
-- Name: idx_chain_detail_extrinsics_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chain_detail_extrinsics_observed ON public.chain_detail_extrinsics USING btree (observed_at);

--
-- Name: idx_github_accounts_github_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_github_accounts_github_user_id ON public.github_accounts USING btree (github_user_id);

--
-- Name: idx_hotkey_alpha_captured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hotkey_alpha_captured ON public.hotkey_alpha USING btree (captured_at);

--
-- Name: idx_hotkey_alpha_netuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hotkey_alpha_netuid ON public.hotkey_alpha USING btree (netuid, total_alpha DESC);

--
-- Name: idx_hotkey_alpha_passes_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hotkey_alpha_passes_completed ON public.hotkey_alpha_passes USING btree (completed_at DESC);

--
-- Name: idx_lane_health_lane_checked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lane_health_lane_checked ON public.lane_health USING btree (lane, checked_at DESC);

--
-- Name: idx_lane_health_stale; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lane_health_stale ON public.lane_health USING btree (checked_at DESC) WHERE (verdict = 'stale'::text);

--
-- Name: idx_neuron_daily_hotkey_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neuron_daily_hotkey_date ON public.neuron_daily USING btree (hotkey, snapshot_date);

--
-- Name: idx_neuron_daily_permit_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neuron_daily_permit_date ON public.neuron_daily USING btree (validator_permit, snapshot_date);

--
-- Name: idx_neuron_daily_snapshot_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neuron_daily_snapshot_date ON public.neuron_daily USING btree (snapshot_date);

--
-- Name: idx_neurons_hotkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neurons_hotkey ON public.neurons USING btree (hotkey);

--
-- Name: idx_neurons_netuid_permit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neurons_netuid_permit ON public.neurons USING btree (netuid, validator_permit);

--
-- Name: idx_neurons_passes_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_neurons_passes_completed ON public.neurons_passes USING btree (completed_at DESC);

--
-- Name: idx_nominator_positions_hotkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nominator_positions_hotkey ON public.nominator_positions USING btree (hotkey, netuid);

--
-- Name: idx_nominator_positions_passes_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nominator_positions_passes_completed ON public.nominator_positions_passes USING btree (completed_at DESC);

--
-- Name: idx_revenue_failures_netuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_revenue_failures_netuid ON public.revenue_probe_failures USING btree (netuid, observed_at DESC);

--
-- Name: idx_revenue_obs_netuid_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_revenue_obs_netuid_period ON public.revenue_observations USING btree (netuid, period DESC);

--
-- Name: idx_revenue_obs_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_revenue_obs_period ON public.revenue_observations USING btree (period DESC);

--
-- Name: idx_rpc_accounts_ss58; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rpc_accounts_ss58 ON public.rpc_accounts USING btree (ss58);

--
-- Name: idx_self_health_checks_recent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_self_health_checks_recent ON public.self_health_checks USING btree (component, checked_at_ms DESC);

--
-- Name: idx_self_health_daily_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_self_health_daily_day ON public.self_health_daily USING btree (day DESC);

--
-- Name: idx_subnet_burn_history_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_burn_history_observed ON public.subnet_burn_history USING btree (observed_at);

--
-- Name: idx_subnet_dereg_daily_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_dereg_daily_date ON public.subnet_deregistration_daily USING btree (snapshot_date DESC);

--
-- Name: idx_subnet_dereg_daily_netuid_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_dereg_daily_netuid_date ON public.subnet_deregistration_daily USING btree (netuid, snapshot_date DESC);

--
-- Name: idx_subnet_hyperparams_history_netuid_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_hyperparams_history_netuid_observed ON public.subnet_hyperparams_history USING btree (netuid, observed_at DESC, id DESC);

--
-- Name: idx_subnet_lifecycle_netuid_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_lifecycle_netuid_time ON public.subnet_lifecycle USING btree (netuid, observed_at DESC);

--
-- Name: idx_subnet_lifecycle_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_lifecycle_time ON public.subnet_lifecycle USING btree (observed_at DESC);

--
-- Name: idx_subnet_snapshots_date_netuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnet_snapshots_date_netuid ON public.subnet_snapshots USING btree (snapshot_date, netuid);

--
-- Name: idx_subnets_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subnets_source ON public.subnets USING btree (source);

--
-- Name: idx_surface_checks_netuid_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_checks_netuid_time ON public.surface_checks USING btree (netuid, checked_at DESC);

--
-- Name: idx_surface_checks_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_checks_time ON public.surface_checks USING btree (checked_at DESC);

--
-- Name: idx_surface_failure_daily_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_failure_daily_day ON public.surface_failure_daily USING btree (day DESC, netuid);

--
-- Name: idx_surface_history_subnet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_history_subnet ON public.surface_history USING btree (subnet_netuid, recorded_at DESC);

--
-- Name: idx_surface_history_surface; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_history_surface ON public.surface_history USING btree (surface_id, recorded_at DESC);

--
-- Name: idx_surface_status_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_surface_status_key ON public.surface_status USING btree (surface_key) WHERE (surface_key IS NOT NULL);

--
-- Name: idx_surface_status_netuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_status_netuid ON public.surface_status USING btree (netuid);

--
-- Name: idx_surface_uptime_daily_key_day; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_surface_uptime_daily_key_day ON public.surface_uptime_daily USING btree (surface_key, day) WHERE (surface_key IS NOT NULL);

--
-- Name: idx_surface_uptime_daily_netuid_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surface_uptime_daily_netuid_day ON public.surface_uptime_daily USING btree (netuid, day DESC);

--
-- Name: idx_surfaces_probe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surfaces_probe ON public.surfaces USING btree (probe_eligible, review_state) WHERE probe_eligible;

--
-- Name: idx_surfaces_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surfaces_provider ON public.surfaces USING btree (provider_id);

--
-- Name: idx_surfaces_subnet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_surfaces_subnet ON public.surfaces USING btree (subnet_netuid);

--
-- Name: idx_tao_usd_index_observed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tao_usd_index_observed ON public.tao_usd_index USING btree (observed_at DESC);

--
-- Name: idx_validator_nominator_counts_passes_completed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_validator_nominator_counts_passes_completed ON public.validator_nominator_counts_passes USING btree (completed_at DESC);

--
-- Name: idx_wps_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wps_address ON public.watch_push_subscriptions USING btree (address, created_at DESC);

--
-- Name: subnet_emission_enabled_history_netuid_observed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX subnet_emission_enabled_history_netuid_observed_idx ON public.subnet_emission_enabled_history USING btree (netuid, observed_at DESC);

--
-- Name: ux_surface_failure_daily_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_surface_failure_daily_key ON public.surface_failure_daily USING btree (day, netuid, kind, classification) NULLS NOT DISTINCT;

--
-- Name: chain_alert_deliveries chain_alert_deliveries_trigger_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chain_alert_deliveries
    ADD CONSTRAINT chain_alert_deliveries_trigger_id_fkey FOREIGN KEY (trigger_id) REFERENCES public.chain_alert_triggers(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--
