import { generate } from "@graphql-codegen/cli";
import { promises as fs } from "node:fs";
import path from "node:path";
import { printSchema } from "graphql";
import codegenConfig from "../codegen.ts";
import { buildGeneratedSchema } from "../schemas-src/graphql/build-schema.ts";
import { repoRoot } from "./lib.ts";
import type { OpenApiParameters } from "../schemas-src/graphql/query-arguments.ts";

// Runs @graphql-codegen/cli's programmatic API against codegen.ts
// (types-epic D, #7862). `generate(config, false)` returns the generated
// output in-memory instead of writing it -- used directly here (single
// source of truth for "what should generated/graphql/types.ts contain"),
// and reused by validate-graphql-types-drift.ts's stale-check so the two
// scripts can never compute a different "expected" content.
//
// ## The SDL is the first output (#10214)
//
// Until #10214 the schema codegen read was `src/graphql-sdl.ts` -- 6,582
// hand-written lines, the last surface not built from the shared Zod contract.
// Everything it contained is declared in `schemas-src/graphql/` (the
// build-schema.ts header lists the six sources), so the SDL is emitted here
// from `buildGeneratedSchema()` and codegen runs against the emitted module.
//
// ONE step, not two, deliberately: codegen READS the schema module, so a
// separate build step would demand an ordering both of scripts/build.ts's step
// lists have to state and can state differently. Emitting first inside the
// same function makes the order a fact of the code. It also means the drift
// gate covers both artifacts by iterating one outputs array -- a stale
// schema.ts fails the same check a stale types.ts always has.
//
// ## Why the runtime gets a printed STRING and not the GraphQLSchema
//
// `buildGeneratedSchema()` costs ~1s of module-scope work (Zod -> JSON Schema
// -> GraphQL type construction); Workers enforce a startup-CPU limit of
// ~400ms, and the api Worker's init already spends most of it. Printing at
// build time leaves the runtime doing what it always did -- `buildSchema(SDL)`,
// ~16ms -- and keeps the resolver model unchanged: an SDL-built schema carries
// no resolver map, which src/graphql.ts relies on (rootValue via the default
// field resolver, with `subscribe` and the two nested-list resolvers attached
// by hand after the fact).
//
// `printSchema` and never string concatenation: the printer owns SDL syntax
// (escaping, block strings, field order), and a generator that assembled
// source text would be a second, worse printer.

/** Where the emitted SDL module lands, repo-relative. */
export const GRAPHQL_SCHEMA_PATH = "generated/graphql/schema.ts";

const OPENAPI_PATH = "public/metagraph/openapi.json";

/**
 * The template-literal escapes, applied in this order (backslash first, or the
 * escapes just added would themselves be escaped). Ten descriptions carry a
 * backtick today (Zod `.describe()` prose like "Distinct from `generated_at`"),
 * so emitting raw would truncate the literal at the first one. The COOKED
 * value -- what the runtime, codegen's graphql-tag-pluck (which parses the
 * module and resolves escapes), and every gate that imports `SDL` sees -- is
 * byte-identical to the printed SDL.
 */
function asTemplateLiteral(sdl: string): string {
  return sdl
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");
}

async function generateGraphqlSchemaModule(): Promise<{
  filename: string;
  content: string;
}> {
  const openapi = JSON.parse(
    await fs.readFile(path.join(repoRoot, OPENAPI_PATH), "utf8"),
  ) as OpenApiParameters;
  const { schema } = buildGeneratedSchema(openapi);
  const sdl = printSchema(schema);
  const content = `// GENERATED by scripts/generate-graphql-types.ts -- do not edit (#10214).
//
// The published GraphQL SDL, printed from the schema
// schemas-src/graphql/build-schema.ts assembles out of the Zod components,
// the published-name declarations, QUERY_BINDINGS and the route-derived
// arguments. It replaced src/graphql-sdl.ts, which was the same surface
// maintained by hand.
//
// Regenerate with \`npm run build:graphql-types\`;
// \`validate:graphql-types-drift\` fails CI if the committed copy and a fresh
// build disagree.
//
// The \`/* GraphQL */\` magic comment before the template literal is
// @graphql-tools/graphql-tag-pluck's documented way to extract SDL from a
// plain (non-\`gql\`-tagged) template literal -- codegen.ts's schema pointer
// relies on it. It is a comment, not a tag function, so it changes nothing
// about how this module executes.
export const SDL = /* GraphQL */ \`
${asTemplateLiteral(sdl)}\`;
`;
  return { filename: GRAPHQL_SCHEMA_PATH, content };
}

export async function generateGraphqlTypes(
  options: { silent?: boolean } = {},
): Promise<{ filename: string; content: string }[]> {
  const schemaModule = await generateGraphqlSchemaModule();
  const typeOutputs = await generate(
    { ...codegenConfig, cwd: repoRoot, silent: options.silent ?? false },
    false,
  );
  return [schemaModule, ...typeOutputs];
}

if (import.meta.url === `file://${process.argv[1]}`) {
  // The schema module is written BEFORE codegen runs, because codegen reads
  // it from disk. Calling generateGraphqlTypes() here instead would hand
  // codegen the COMMITTED schema -- right for the drift gate, where a stale
  // schema.ts must fail on its own entry, and exactly wrong for a build.
  const schemaModule = await generateGraphqlSchemaModule();
  const target = path.join(repoRoot, schemaModule.filename);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, schemaModule.content, "utf8");
  const outputs = await generate(
    { ...codegenConfig, cwd: repoRoot, silent: false },
    false,
  );
  for (const output of outputs) {
    await fs.mkdir(path.dirname(output.filename), { recursive: true });
    await fs.writeFile(output.filename, output.content, "utf8");
  }
  console.log("Generated GraphQL schema module and resolver/argument types.");
}
