// registry/featured-validators.json -> generated/featured-validators.ts (#11080).
//
// WHY GENERATE A CONSTANT INSTEAD OF READING THE JSON AT RUNTIME.
// The consumer is workers/data-api.ts, which sits at the Worker STARTUP CPU
// limit: any added module-scope work -- a JSON parse, a Zod construction --
// tips it over, and that has taken the deploy down before. A frozen string
// array costs nothing at boot.
//
// It also means the badge cannot depend on a fetch succeeding. A partner's
// badge disappearing because an artifact request failed would be a worse
// failure than the one this replaces.
//
// The JSON stays the source of truth and this file is derived, so a change is
// still a reviewed pull request against the registry -- which is the whole
// point of keeping commercial curation in git.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { repoRoot } from "./lib.ts";
import { FeaturedValidatorsFileSchema } from "../schemas-src/artifacts/featured-validators.ts";

export const SOURCE_PATH = "registry/featured-validators.json";
export const GENERATED_PATH = "generated/featured-validators.ts";

/** Parse + validate the registry file, returning the sorted hotkeys. */
export function featuredHotkeysFrom(raw: string): string[] {
  const parsed = FeaturedValidatorsFileSchema.parse(JSON.parse(raw));
  const hotkeys = parsed.featured.map((entry) => entry.hotkey);
  const unique = new Set(hotkeys);
  if (unique.size !== hotkeys.length) {
    // A duplicate is silent otherwise: the Set the worker builds would swallow
    // it, and the registry would carry two entries for one relationship with
    // no way to tell which one is current.
    throw new Error(
      `${SOURCE_PATH}: duplicate hotkey(s) — each validator may be featured once`,
    );
  }
  // Sorted so the generated file is stable regardless of registry ordering;
  // an unsorted emit would show a diff every time an entry moved.
  return [...unique].sort();
}

export function render(hotkeys: string[]): string {
  const entries = hotkeys.map((h) => `  ${JSON.stringify(h)},`).join("\n");
  return `// GENERATED by scripts/generate-featured-validators.ts — do not edit.
// Source: ${SOURCE_PATH}
//
// The hotkeys carrying a partnership, sponsorship or agreement (#11080).
// Frozen at module scope so workers/data-api.ts pays nothing at boot for it —
// see the generator's header for why this is not a runtime read.

export const FEATURED_HOTKEYS: readonly string[] = Object.freeze([
${entries}
]);

/** The same list as a Set, for the membership test the validator builder does. */
export const FEATURED_HOTKEY_SET: ReadonlySet<string> = new Set(FEATURED_HOTKEYS);
`;
}

async function main(): Promise<void> {
  const raw = readFileSync(path.join(repoRoot, SOURCE_PATH), "utf8");
  const hotkeys = featuredHotkeysFrom(raw);
  writeFileSync(path.join(repoRoot, GENERATED_PATH), render(hotkeys));
  process.stdout.write(
    `wrote ${GENERATED_PATH} (${hotkeys.length} featured hotkey(s))\n`,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
