// Types and column tuples for the four Iceberg tables, from a committed schema
// snapshot (#10315).
//
// THE LAKEHOUSE WAS THE ONE STORE WHOSE SCHEMA GENERATED NOTHING. Everywhere
// else the schema is the contract and types fall out of it -- `schemas-src/` ->
// openapi.json -> `ApiSchema<>`, and `generated/db/schema.json` ->
// `generated/db/types.ts` for every Neon table (#10261). The Iceberg tables
// have a live schema in the catalog and every producer built rows against it
// FROM MEMORY: the Rust decoder constructs row maps by hand, and so does every
// ad-hoc projector.
//
// WHEN THE ONLY CHECK FIRES IS THE PROBLEM. `iceberg_load.py` reads column
// types off the live table and casts the incoming rows to them, which is
// correct and stays. But that cast is the FIRST thing that compares a
// producer's idea of the schema to the real one, and it happens inside the
// append -- the one irreversible step. A decoder that renames a column
// compiles, tests, runs, produces rows, and fails at the last possible moment.
// `--dry-run` exists because that is too late, which is an admission that the
// check belongs earlier.
//
// This moves it earlier for anything written in this repo: import the column
// tuple instead of hand-typing eleven names.
//
// WHAT THIS CANNOT DO, and the snapshot boundary is the same one
// generate-db-types.ts documents: nothing readable from a pull request can
// catch the LAKEHOUSE having moved. `npm run refresh:lakehouse-schema` is that
// check and it needs R2_CATALOG_TOKEN, so it runs out of band against the real
// catalog. The drift validator only asserts that the committed types match the
// committed snapshot -- that the repo is internally consistent.
import { readFileSync } from "node:fs";
import path from "node:path";
import { repoRoot } from "./lib.ts";

export const SNAPSHOT_PATH = "generated/lakehouse/schema.json";
export const TYPES_PATH = "generated/lakehouse/types.ts";

export interface LakehouseColumn {
  table: string;
  field_id: number;
  column: string;
  type: string;
  required: boolean;
}

export function readSnapshot(): LakehouseColumn[] {
  return JSON.parse(
    readFileSync(path.join(repoRoot, SNAPSHOT_PATH), "utf8"),
  ) as LakehouseColumn[];
}

/**
 * Iceberg primitive -> TypeScript.
 *
 * `long` IS `number`, unlike `int8` in generated/db/types.ts, and the
 * difference is the reader rather than a preference. Postgres `int8` arrives
 * through node-postgres, whose parser leaves a value a STRING when it is not
 * exactly representable (src/pg-sql.ts), so the type has to admit both. R2 SQL
 * answers JSON, so a `long` is already a JS number by the time any code here
 * sees it -- typing it `number | string` would describe a shape that cannot
 * occur and push a coercion onto every call site.
 *
 * Every `long` in these four tables is a block number, an index, or
 * epoch-milliseconds. The largest is ~1.79e12 against a safe ceiling of
 * ~9.01e15, so the representable range is not close.
 */
const TS_TYPE: Readonly<Record<string, string>> = {
  boolean: "boolean",
  double: "number",
  int: "number",
  long: "number",
  string: "string",
};

const pascal = (table: string) =>
  table
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

export function emitTypes(columns: LakehouseColumn[]): string {
  const tables = [...new Set(columns.map((c) => c.table))];
  const out: string[] = [
    "// GENERATED by scripts/generate-lakehouse-types.ts from",
    `// ${SNAPSHOT_PATH}. Do not edit. Run \`npm run build:lakehouse-types\``,
    "// after re-snapshotting the catalog with `npm run refresh:lakehouse-schema`.",
    "//",
    "// One interface per Iceberg table in the `chain` namespace, plus the",
    "// column tuple in FIELD-ID ORDER -- which is the order the loader appends",
    "// and therefore the order a hand-built row must be written in.",
    "",
  ];
  for (const table of tables) {
    const cols = columns
      .filter((c) => c.table === table)
      .sort((a, b) => a.field_id - b.field_id);
    const unknown = cols.filter((c) => !TS_TYPE[c.type]);
    if (unknown.length > 0) {
      throw new Error(
        `unmapped Iceberg type(s) in ${table}: ` +
          unknown.map((c) => `${c.column}:${c.type}`).join(", ") +
          " -- add it to TS_TYPE rather than letting it fall back",
      );
    }
    out.push(`/** \`chain.${table}\` */`);
    out.push(`export interface ${pascal(table)}Row {`);
    for (const c of cols) {
      const optional = c.required ? "" : " | null";
      out.push(`  ${c.column}: ${TS_TYPE[c.type]}${optional};`);
    }
    out.push("}");
    out.push("");
    out.push(`/** \`chain.${table}\` columns, in field-id order. */`);
    out.push(
      `export const ${table.toUpperCase()}_COLUMNS = [`,
      ...cols.map((c) => `  ${JSON.stringify(c.column)},`),
      "] as const;",
      "",
    );
  }
  out.push("/** Every Iceberg table this repo reads, by name. */");
  out.push(
    "export const LAKEHOUSE_TABLES = [",
    ...tables.map((t) => `  ${JSON.stringify(t)},`),
    "] as const;",
    "",
  );
  return out.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { writeFileSync } = await import("node:fs");
  writeFileSync(path.join(repoRoot, TYPES_PATH), emitTypes(readSnapshot()));
  process.stdout.write(`wrote ${TYPES_PATH}\n`);
}
