// src/rpc-usage-capture.ts -> generated/rpc-usage-slots.json (#11078).
//
// WHY THIS EXISTS. Analytics Engine rows have NO column names -- a data point is
// blob1..blob20 and double1..double20, and the mapping from meaning to slot
// lives in exactly one place: `RPC_USAGE_BLOBS` / `RPC_USAGE_DOUBLES` in
// src/rpc-usage-capture.ts. That file is emphatic that the mapping is append
// only, because old data points keep whatever a slot meant when they were
// written and there is no ALTER to fix them.
//
// The hot-tier reader already imports those constants rather than retyping
// "blob3". The AE -> Iceberg exporter (metagraphed-infra) could not: it is
// Python, and vendoring a `.ts` file into a Python consumer would mean parsing
// TypeScript at runtime, which is worse than the duplication it replaces. So it
// carried a hand-maintained copy, and a hand-maintained copy of an unmigratable
// schema is the highest-consequence kind: a slot that silently disagrees does
// not error, it writes the wrong column.
//
// This emits the mapping as JSON, which infra vendors byte-for-byte through the
// mechanism it already has (`scripts/check-vendored-sync.py`, whose header
// records an audit that found 7 of 8 vendored pairs already drifted, in both
// directions -- the mechanism exists precisely because hand-copying does not
// survive two repos).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { repoRoot } from "./lib.ts";
import {
  RPC_USAGE_BLOBS,
  RPC_USAGE_DATASET,
  RPC_USAGE_DOUBLES,
} from "../src/rpc-usage-capture.ts";

export const GENERATED_PATH = "generated/rpc-usage-slots.json";

/**
 * The slot map as JSON, sorted by SLOT rather than by name.
 *
 * Sorted by slot because that is the axis the append-only rule runs along: a
 * reviewer scanning this diff should see `double5` appear after `double4`, and
 * should see an existing slot change position as the loud thing it is. Sorting
 * by name would scatter that.
 */
export function render(): string {
  const bySlot = (a: [string, string], b: [string, string]): number => {
    const n = (s: string): number => Number(s.replace(/^\D+/, ""));
    return n(a[1]) - n(b[1]);
  };
  // Both names, emitted rather than converted. The TS constants are camelCase
  // (`endpointId`) and the lakehouse columns are snake_case (`endpoint_id`), so
  // a consumer would otherwise have to reimplement a naming convention -- and a
  // convention reimplemented in a second language is the drift this file is
  // here to remove. `pool` has NO column on purpose: it discriminates public
  // from fullnode traffic and the lakehouse table predates it, so the exporter
  // filters on it and never writes it.
  const snake = (name: string): string =>
    name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
  const entries = (map: Record<string, string>) =>
    Object.entries(map)
      .sort(bySlot)
      .map(([name, slot]) => ({
        name,
        slot,
        column: name === "pool" ? null : snake(name),
      }));
  const body = {
    $comment:
      "GENERATED by scripts/generate-rpc-usage-slots.ts from src/rpc-usage-capture.ts. Do not edit. APPEND ONLY: an occupied slot's meaning can never change, because data points written under the old meaning cannot be migrated.",
    dataset: RPC_USAGE_DATASET,
    blobs: entries(RPC_USAGE_BLOBS),
    doubles: entries(RPC_USAGE_DOUBLES),
  };
  return `${JSON.stringify(body, null, 2)}\n`;
}

async function main(): Promise<void> {
  writeFileSync(path.join(repoRoot, GENERATED_PATH), render());
  const slots =
    Object.keys(RPC_USAGE_BLOBS).length + Object.keys(RPC_USAGE_DOUBLES).length;
  process.stdout.write(`wrote ${GENERATED_PATH} (${slots} slot(s))\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
