// Generates src/components/metagraphed/design/design-tokens.generated.ts from
// packages/ui-kit/src/styles.css (#11627).
//
// `/design/primitives` documents the design system, and the Tokens section
// lists every token with its light and dark value. Written by hand that table
// is wrong the first time a colour moves -- and wrong on the one page a reader
// consults BECAUSE they do not want to read the stylesheet. So it is generated
// from the stylesheet, committed like every other generated artifact here
// (content/docs/limits.mdx, content/docs/api-reference), and
// design-tokens.test.ts re-parses the same stylesheet and fails while the two
// disagree.
//
// Re-run after changing a token, from apps/ui:
//
//   npm run generate:design-tokens
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import { parseDesignTokens } from "../src/components/metagraphed/design/parse-design-tokens.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STYLES_PATH = path.join(__dirname, "../../../packages/ui-kit/src/styles.css");
const OUTPUT_PATH = path.join(
  __dirname,
  "../src/components/metagraphed/design/design-tokens.generated.ts",
);

const HEADER = `/* eslint-disable no-restricted-syntax -- the token values ARE raw colours: this
   file is the stylesheet's palette, transcribed. The rule exists to stop a
   component authoring a colour outside the token layer; nothing here authors
   anything. */
// GENERATED by apps/ui/scripts/generate-design-tokens.ts -- do not edit.
// Source: packages/ui-kit/src/styles.css
//
// Re-run \`npm run generate:design-tokens\` (from apps/ui) after changing a
// token. design-tokens.test.ts re-parses the stylesheet and fails while this
// file and it disagree, so the Tokens table on /design/primitives cannot drift
// away from the theme it claims to document.
import type { DesignToken } from "./parse-design-tokens";
`;

function literal(value: string | number | null): string {
  if (value === null) return "null";
  if (typeof value === "number") return String(value);
  return JSON.stringify(value);
}

async function main() {
  const css = await readFile(STYLES_PATH, "utf8");
  const tokens = parseDesignTokens(css);
  if (tokens.length === 0) {
    throw new Error(`No tokens parsed from ${STYLES_PATH}; refusing to write an empty table.`);
  }
  const rows = tokens
    .map(
      (token) =>
        `{ name: ${literal(token.name)}, light: ${literal(token.light)}, dark: ${literal(
          token.dark,
        )}, theme: ${literal(token.theme)}, refs: ${literal(token.refs)} },`,
    )
    .join("\n");
  const raw = `${HEADER}
export const DESIGN_TOKENS: readonly DesignToken[] = [
${rows}
];
`;
  const config = await prettier.resolveConfig(OUTPUT_PATH);
  const formatted = await prettier.format(raw, { ...config, parser: "typescript" });
  await writeFile(OUTPUT_PATH, formatted, "utf8");
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_PATH)} (${tokens.length} tokens)`);
}

await main();
