/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.data.jsonc --include-runtime=false --env-interface=DataApiEnv workers/data-api.worker-configuration.d.ts` (hash: b91fa594b5be6ca8a49a65b9e5ee0741)
interface __BaseEnv_DataApiEnv {
	METAGRAPH_CONTROL: KVNamespace;
	METAGRAPH_ARCHIVE: R2Bucket;
	D1_STATE: D1Database;
	D1_RETAINED_BLOCKS: D1Database;
	SYNC_BATCHES: Queue;
	ALERT_TRIGGER_CREATE_RATE_LIMITER: RateLimit;
	WALLET_AUTH_RATE_LIMITER: RateLimit;
	ACCOUNT_KEYS_MINT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	NATIVE_HISTORY_ASSET_RELEASE: "bfb62b96bdf6b1a6f1723ae14f461184e7b0aefb18f7560c458929ed2abe727c:307828";
	ACCOUNT_HISTORY_ASSET_RELEASE: "39648ba9e6cd6e5acd955bf873dd4264763496921221811d978453d1f5a75598:401638";
	HISTORY_ASSET_RELEASE: "2f33d8c5e292dc509354231d3e5fd75ac0f50cdb0b549b98107d5c93bbda1c1f:25282";
	NATIVE_PROJECTIONS: "enabled";
	RETAINED_BLOCKS_NETWORKS: "mainnet,testnet";
	D1_EXPORT_REVISIONS: "enabled";
	D1_STATE_TABLES: "account_balances,account_balances_passes,account_identity,account_identity_history,account_position_daily,api_key_blocks,api_key_usage_daily,api_keys,api_quota_daily,api_usage_rollup,attribution_candidates,attribution_sweeps,blocks_head,chain_alert_deliveries,chain_alert_triggers,chain_concentration_daily,chain_detail_account_events,chain_detail_blocks,chain_detail_chain_events,chain_detail_extrinsics,compute_declarations,emission_flow_watch,emission_gate_param_history,github_accounts,hotkey_alpha,hotkey_alpha_passes,lane_health,neuron_daily,neurons,neurons_passes,nominator_positions,nominator_positions_passes,nominator_scan_receipts,origin_reachability,providers,raw_capture_state,revenue_observations,revenue_probe_failures,root_basket_capture_completions,root_basket_capture_pages,root_basket_captures,root_basket_current,root_basket_fund_snapshots,root_basket_holdings,root_basket_targets,rpc_accounts,self_health_checks,self_health_daily,subnet_burn_history,subnet_deregistration_daily,subnet_emission_enabled_history,subnet_hyperparams,subnet_hyperparams_history,subnet_identity,subnet_identity_history,subnet_lifecycle,subnet_ownership,subnet_ownership_history,subnet_snapshots,subnets,surface_checks,surface_failure_daily,surface_history,surface_status,surface_uptime_daily,surfaces,tao_usd_index,treasury_readings,validator_nominator_counts,validator_nominator_counts_passes,watch_push_subscriptions";
	UNKEY_API_ID: "api_2Dv8cVjrTSiD";
	METAGRAPH_NEURONS_SOURCE: "data-api";
	METAGRAPH_SUBNET_HYPERPARAMS_SOURCE: "data-api";
	METAGRAPH_ACCOUNT_IDENTITY_SOURCE: "data-api";
	SYNC_QUEUE_LANES: "account-balances,hotkey-alpha,validator-nominator-counts,nominator-positions,chain-detail";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
	POSTHOG_TRACES_SAMPLE_RATE: "0.002";
	NATIVE_HISTORY_ASSETS: Fetcher /* metagraphed-history-native-01c21211f2f4-0 */;
	NATIVE_HISTORY_ASSETS_0: Fetcher /* metagraphed-history-native-01c21211f2f4-0 */;
	NATIVE_HISTORY_ASSETS_1: Fetcher /* metagraphed-history-native-01c21211f2f4-1 */;
	NATIVE_HISTORY_ASSETS_2: Fetcher /* metagraphed-history-native-01c21211f2f4-2 */;
	NATIVE_HISTORY_ASSETS_3: Fetcher /* metagraphed-history-native-01c21211f2f4-3 */;
	NATIVE_HISTORY_ASSETS_4: Fetcher /* metagraphed-history-native-01c21211f2f4-4 */;
	NATIVE_HISTORY_ASSETS_5: Fetcher /* metagraphed-history-native-01c21211f2f4-5 */;
	NATIVE_HISTORY_ASSETS_6: Fetcher /* metagraphed-history-native-01c21211f2f4-6 */;
	NATIVE_HISTORY_ASSETS_7: Fetcher /* metagraphed-history-native-01c21211f2f4-7 */;
	NATIVE_HISTORY_ASSETS_8: Fetcher /* metagraphed-history-native-01c21211f2f4-8 */;
	NATIVE_HISTORY_ASSETS_9: Fetcher /* metagraphed-history-native-01c21211f2f4-9 */;
	NATIVE_HISTORY_ASSETS_a: Fetcher /* metagraphed-history-native-01c21211f2f4-a */;
	NATIVE_HISTORY_ASSETS_b: Fetcher /* metagraphed-history-native-01c21211f2f4-b */;
	NATIVE_HISTORY_ASSETS_c: Fetcher /* metagraphed-history-native-01c21211f2f4-c */;
	NATIVE_HISTORY_ASSETS_d: Fetcher /* metagraphed-history-native-01c21211f2f4-d */;
	NATIVE_HISTORY_ASSETS_e: Fetcher /* metagraphed-history-native-01c21211f2f4-e */;
	NATIVE_HISTORY_ASSETS_f: Fetcher /* metagraphed-history-native-01c21211f2f4-f */;
	ACCOUNT_HISTORY_ASSETS: Fetcher /* metagraphed-history-accounts-f090a73e69b0-meta */;
	ACCOUNT_HISTORY_ASSETS_0: Fetcher /* metagraphed-history-accounts-f090a73e69b0-0 */;
	ACCOUNT_HISTORY_ASSETS_1: Fetcher /* metagraphed-history-accounts-f090a73e69b0-1 */;
	ACCOUNT_HISTORY_ASSETS_2: Fetcher /* metagraphed-history-accounts-f090a73e69b0-2 */;
	ACCOUNT_HISTORY_ASSETS_3: Fetcher /* metagraphed-history-accounts-f090a73e69b0-3 */;
	ACCOUNT_HISTORY_ASSETS_4: Fetcher /* metagraphed-history-accounts-f090a73e69b0-4 */;
	ACCOUNT_HISTORY_ASSETS_5: Fetcher /* metagraphed-history-accounts-f090a73e69b0-5 */;
	ACCOUNT_HISTORY_ASSETS_6: Fetcher /* metagraphed-history-accounts-f090a73e69b0-6 */;
	ACCOUNT_HISTORY_ASSETS_7: Fetcher /* metagraphed-history-accounts-f090a73e69b0-7 */;
	ACCOUNT_HISTORY_ASSETS_8: Fetcher /* metagraphed-history-accounts-f090a73e69b0-8 */;
	ACCOUNT_HISTORY_ASSETS_9: Fetcher /* metagraphed-history-accounts-f090a73e69b0-9 */;
	ACCOUNT_HISTORY_ASSETS_a: Fetcher /* metagraphed-history-accounts-f090a73e69b0-a */;
	ACCOUNT_HISTORY_ASSETS_b: Fetcher /* metagraphed-history-accounts-f090a73e69b0-b */;
	ACCOUNT_HISTORY_ASSETS_c: Fetcher /* metagraphed-history-accounts-f090a73e69b0-c */;
	ACCOUNT_HISTORY_ASSETS_d: Fetcher /* metagraphed-history-accounts-f090a73e69b0-d */;
	ACCOUNT_HISTORY_ASSETS_e: Fetcher /* metagraphed-history-accounts-f090a73e69b0-e */;
	ACCOUNT_HISTORY_ASSETS_f: Fetcher /* metagraphed-history-accounts-f090a73e69b0-f */;
	HISTORY_ASSETS: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-meta */;
	HISTORY_ASSETS_0: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-0 */;
	HISTORY_ASSETS_1: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-1 */;
	HISTORY_ASSETS_2: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-2 */;
	HISTORY_ASSETS_3: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-3 */;
	HISTORY_ASSETS_4: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-4 */;
	HISTORY_ASSETS_5: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-5 */;
	HISTORY_ASSETS_6: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-6 */;
	HISTORY_ASSETS_7: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-7 */;
	HISTORY_ASSETS_8: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-8 */;
	HISTORY_ASSETS_9: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-9 */;
	HISTORY_ASSETS_a: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-a */;
	HISTORY_ASSETS_b: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-b */;
	HISTORY_ASSETS_c: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-c */;
	HISTORY_ASSETS_d: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-d */;
	HISTORY_ASSETS_e: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-e */;
	HISTORY_ASSETS_f: Fetcher /* metagraphed-history-extrinsics-2f33d8c5e292-f */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./data-api");
	}
	interface Env extends __BaseEnv_DataApiEnv {}
}
interface DataApiEnv extends __BaseEnv_DataApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NATIVE_HISTORY_ASSET_RELEASE" | "ACCOUNT_HISTORY_ASSET_RELEASE" | "HISTORY_ASSET_RELEASE" | "NATIVE_PROJECTIONS" | "RETAINED_BLOCKS_NETWORKS" | "D1_EXPORT_REVISIONS" | "D1_STATE_TABLES" | "UNKEY_API_ID" | "METAGRAPH_NEURONS_SOURCE" | "METAGRAPH_SUBNET_HYPERPARAMS_SOURCE" | "METAGRAPH_ACCOUNT_IDENTITY_SOURCE" | "SYNC_QUEUE_LANES" | "POSTHOG_EXCEPTION_STORM_WINDOW_MS" | "POSTHOG_TRACES_SAMPLE_RATE">> {}
}
