/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.data.jsonc --include-runtime=false --env-interface=DataApiEnv workers/data-api.worker-configuration.d.ts` (hash: f7070c52b997f863ee78f79d8e8f3fdd)
interface __BaseEnv_DataApiEnv {
	METAGRAPH_CONTROL: KVNamespace;
	METAGRAPH_ARCHIVE: R2Bucket;
	D1_STATE: D1Database;
	HYPERDRIVE: Hyperdrive;
	SYNC_BATCHES: Queue;
	ALERT_TRIGGER_CREATE_RATE_LIMITER: RateLimit;
	WALLET_AUTH_RATE_LIMITER: RateLimit;
	ACCOUNT_KEYS_MINT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	D1_EXPORT_REVISIONS: "enabled";
	D1_STATE_TABLES: "lane_health,attribution_candidates,attribution_sweeps,origin_reachability,compute_declarations,rpc_accounts,github_accounts,api_keys,api_key_blocks,api_key_usage_daily,api_quota_daily,api_usage_rollup,chain_alert_triggers,chain_alert_deliveries,watch_push_subscriptions,raw_capture_state,emission_gate_param_history,subnet_emission_enabled_history,emission_flow_watch,subnet_deregistration_daily";
	NEON_WRITE_BUFFER_LANES: "neurons,subnet-hyperparams,subnet-identity,account-identity,nominator-positions,account-balances,hotkey-alpha,validator-nominator-counts,tao-usd-index";
	UNKEY_API_ID: "api_2Dv8cVjrTSiD";
	METAGRAPH_NEURONS_SOURCE: "data-api";
	METAGRAPH_SUBNET_HYPERPARAMS_SOURCE: "data-api";
	METAGRAPH_ACCOUNT_IDENTITY_SOURCE: "data-api";
	SYNC_QUEUE_LANES: "account-balances,hotkey-alpha,validator-nominator-counts,nominator-positions,chain-detail";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
	POSTHOG_TRACES_SAMPLE_RATE: "0.002";
	NEON_WRITE_BUFFER: DurableObjectNamespace /* NeonWriteBufferHub from metagraphed */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./data-api");
	}
	interface Env extends __BaseEnv_DataApiEnv {}
}
interface DataApiEnv extends __BaseEnv_DataApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "D1_EXPORT_REVISIONS" | "D1_STATE_TABLES" | "NEON_WRITE_BUFFER_LANES" | "UNKEY_API_ID" | "METAGRAPH_NEURONS_SOURCE" | "METAGRAPH_SUBNET_HYPERPARAMS_SOURCE" | "METAGRAPH_ACCOUNT_IDENTITY_SOURCE" | "SYNC_QUEUE_LANES" | "POSTHOG_EXCEPTION_STORM_WINDOW_MS" | "POSTHOG_TRACES_SAMPLE_RATE">> {}
}
