/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.data.jsonc --include-runtime=false workers/data-api.worker-configuration.d.ts` (hash: 45493f963c75dceacd887d8dc593ed58)
interface __BaseEnv_Env {
	METAGRAPH_CONTROL: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	SYNC_BATCHES: Queue;
	ALERT_TRIGGER_CREATE_RATE_LIMITER: RateLimit;
	WALLET_AUTH_RATE_LIMITER: RateLimit;
	ACCOUNT_KEYS_MINT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	NEON_WRITE_BUFFER_LANES: "raw-capture-state,neurons,subnet-hyperparams,account-identity,nominator-positions,account-balances,hotkey-alpha,validator-nominator-counts,tao-usd-index";
	UNKEY_API_ID: "api_2Dv8cVjrTSiD";
	METAGRAPH_NEURONS_SOURCE: "d1";
	NEON_DUAL_WRITE_LANES: "neurons,nominator-positions,account-balances,hotkey-alpha,validator-nominator-counts,subnet-hyperparams,account-identity,subnet-identity,chain-detail,blocks-head,raw-capture-state";
	NEON_SOLE_STORE_TABLES: "rpc_accounts,github_accounts,api_keys,api_key_blocks,api_key_usage_daily,api_quota_daily,api_usage_rollup,chain_alert_triggers,chain_alert_deliveries,watch_push_subscriptions,neurons,neuron_daily,account_position_daily,surface_checks,surface_status,surface_uptime_daily,surface_failure_daily,subnet_snapshots,subnet_hyperparams,subnet_hyperparams_history,account_identity,account_identity_history,subnet_identity,subnet_identity_history,validator_nominator_counts,chain_concentration_daily,subnet_burn_history,tao_usd_index,nominator_positions,nominator_positions_passes,blocks_head,raw_capture_state,chain_detail_blocks,chain_detail_extrinsics,chain_detail_chain_events,chain_detail_account_events,neurons_passes,validator_nominator_counts_passes,emission_gate_param_history,subnet_emission_enabled_history,subnet_lifecycle,emission_flow_watch,lane_health,account_balances,account_balances_passes,hotkey_alpha,hotkey_alpha_passes,self_health_checks,self_health_daily,subnets,surfaces,providers,surface_history,revenue_observations,revenue_probe_failures,attribution_sweeps,attribution_candidates,origin_reachability";
	METAGRAPH_SUBNET_HYPERPARAMS_SOURCE: "d1";
	METAGRAPH_ACCOUNT_IDENTITY_SOURCE: "d1";
	SYNC_QUEUE_LANES: "account-balances,hotkey-alpha,validator-nominator-counts,nominator-positions,chain-detail";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
	POSTHOG_TRACES_SAMPLE_RATE: "0.002";
	NEON_WRITE_BUFFER: DurableObjectNamespace /* NeonWriteBufferHub from metagraphed */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./data-api");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEON_WRITE_BUFFER_LANES" | "UNKEY_API_ID" | "METAGRAPH_NEURONS_SOURCE" | "NEON_DUAL_WRITE_LANES" | "NEON_SOLE_STORE_TABLES" | "METAGRAPH_SUBNET_HYPERPARAMS_SOURCE" | "METAGRAPH_ACCOUNT_IDENTITY_SOURCE" | "SYNC_QUEUE_LANES" | "POSTHOG_EXCEPTION_STORM_WINDOW_MS" | "POSTHOG_TRACES_SAMPLE_RATE">> {}
}
