/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.registry.jsonc --include-runtime=false --env-interface=RegistrySyncApiEnv workers/registry-sync-api.worker-configuration.d.ts` (hash: f3a3b5a700a1c293c1ef36df5586e78e)
interface __BaseEnv_RegistrySyncApiEnv {
	D1_STATE: D1Database;
	HYPERDRIVE: Hyperdrive;
	REGISTRY_SYNC_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	D1_STATE_TABLES: "lane_health";
	NEON_WRITE_BUFFER_LANES: "neurons,subnet-hyperparams,subnet-identity,account-identity,nominator-positions,account-balances,hotkey-alpha,validator-nominator-counts,tao-usd-index";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
	POSTHOG_TRACES_SAMPLE_RATE: "1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./registry-sync-api");
	}
	interface Env extends __BaseEnv_RegistrySyncApiEnv {}
}
interface RegistrySyncApiEnv extends __BaseEnv_RegistrySyncApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "D1_STATE_TABLES" | "NEON_WRITE_BUFFER_LANES" | "POSTHOG_EXCEPTION_STORM_WINDOW_MS" | "POSTHOG_TRACES_SAMPLE_RATE">> {}
}
