/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.registry.jsonc --include-runtime=false workers/registry-sync-api.worker-configuration.d.ts` (hash: f7b592cf5c33c78f56e587bb5de7fac8)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	REGISTRY_SYNC_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./registry-sync-api");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
