/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.registry.jsonc --include-runtime=false workers/registry-sync-api.worker-configuration.d.ts` (hash: c5c8e3939b33ad3be091bf46fa7e3ce3)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	REGISTRY_SYNC_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	NEON_WRITE_BUFFER_LANES: "raw-capture-state,neurons,subnet-hyperparams,subnet-identity,account-identity,nominator-positions,account-balances,hotkey-alpha,validator-nominator-counts,tao-usd-index";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
	POSTHOG_TRACES_SAMPLE_RATE: "1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./registry-sync-api");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEON_WRITE_BUFFER_LANES" | "POSTHOG_EXCEPTION_STORM_WINDOW_MS" | "POSTHOG_TRACES_SAMPLE_RATE">> {}
}
