/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.wss-lb.jsonc --include-runtime=false workers/wss-lb.worker-configuration.d.ts` (hash: 824ffdf69d769f638db57bc2695c5b6f)
interface __BaseEnv_Env {
	WSS_CONNECT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	METAGRAPHED_API: "https://api.metagraph.sh";
	NETWORKS: "finney,test";
	MAX_BLOCK_LAG: "50";
	HANDSHAKE_TIMEOUT_MS: "5000";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./wss-lb");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
