/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.wss-lb.jsonc --include-runtime=false --env-interface=WssLbWorkerEnv workers/wss-lb.worker-configuration.d.ts` (hash: b3b30195d20c8d6e384997b9efcf2528)
interface __BaseEnv_WssLbWorkerEnv {
	WSS_CONNECT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	METAGRAPHED_API: "https://api.metagraph.sh";
	NETWORKS: "finney,test";
	MAX_BLOCK_LAG: "50";
	HANDSHAKE_TIMEOUT_MS: "5000";
	POSTHOG_EXCEPTION_STORM_WINDOW_MS: "300000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./wss-lb");
	}
	interface Env extends __BaseEnv_WssLbWorkerEnv {}
}
interface WssLbWorkerEnv extends __BaseEnv_WssLbWorkerEnv {}
